using System;
using System.Data;
using System.Configuration;
using System.Collections;
using System.Web;
using System.Web.Security;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.HtmlControls;
using System.Diagnostics;
using System.IO;
using System.Drawing;
using System.Net;

public partial class adswap_publication : System.Web.UI.Page
{

    string username, userid;
    string dateformat, id;
    int j = 0;
    string pubdate1 = "";
    string picturespath = "";// ConfigurationSettings.AppSettings["Pictures_copy_path"].ToString() + "pictures//";
    string default_center = "";//ConfigurationSettings.AppSettings["default_center"].ToString();

    protected void Page_Load(object sender, EventArgs e)
    {
        Response.Expires = -1;
        Response.Buffer = true;
        Response.ExpiresAbsolute = DateTime.Now.AddDays(-1d);
        Response.Expires = -1500;
        Response.CacheControl = "no-cache";

        if (Session["compcode"] != null)
        {
            hiddencompcode.Value = Session["compcode"].ToString();
            hiddenuserid.Value = Session["userid"].ToString();
            hiddenusername.Value = Session["username"].ToString();
            hiddenauto.Value = Session["autogenerated"].ToString();
            hiddendateformat.Value = Session["dateformat"].ToString();
            hiddendefaultcenter.Value = default_center;
            hiddenlogincenter.Value = Session["center"].ToString();
            hiddenAdPicPath.Value = "";// ConfigurationSettings.AppSettings["AdPicturesfilepath"].ToString();
        }
        else
        {
            li.Text = "<script>window.parent.location=\"login.aspx\";</script>";
            return;
        }
        //commented by danish
        /*if (ConfigurationSettings.AppSettings["Localupdate"].ToString() == "1" && ConfigurationSettings.AppSettings["default_center"].ToString().IndexOf(hiddenlogincenter.Value) == -1)
        {
            btnUpload.Attributes.Add("onclick", "return uploadfile()");
       
        }*/
        //added by danish
        /*if (ConfigurationSettings.AppSettings["Localupdate"].ToString() == "1")
        {
            btnUpload.Attributes.Add("onclick", "return uploadfile()");
            Panel1.Visible = false;
            btnSend.Visible = false;
        }*/

        DataSet objDataSet = new DataSet();
        // Read in the XML file
        objDataSet.ReadXml(Server.MapPath("XML/BookingUnit.xml"));
        lblPublicationDate.Text = objDataSet.Tables[0].Rows[0].ItemArray[0].ToString();
        lblPublication.Text = objDataSet.Tables[0].Rows[0].ItemArray[1].ToString();
        lblCenter.Text = objDataSet.Tables[0].Rows[0].ItemArray[2].ToString();
        lblEdition.Text = objDataSet.Tables[0].Rows[0].ItemArray[3].ToString();
        lblSupplement.Text = objDataSet.Tables[0].Rows[0].ItemArray[4].ToString();
        //lblpageno.Text = objDataSet.Tables[0].Rows[0].ItemArray[11].ToString();
        DataSet objDataSetbu = new DataSet();
        // Read in the XML file
        objDataSetbu.ReadXml(Server.MapPath("XML/button.xml"));
        btnQuery.ImageUrl = objDataSetbu.Tables[0].Rows[0].ItemArray[3].ToString();
        btnCancel.ImageUrl = objDataSetbu.Tables[0].Rows[0].ItemArray[5].ToString();
        btnExit.ImageUrl = objDataSetbu.Tables[0].Rows[0].ItemArray[11].ToString();
        btnView.Text = objDataSetbu.Tables[0].Rows[0].ItemArray[12].ToString();

        //DataSet objDataSetpath = new DataSet();
        //objDataSetpath.ReadXml(Server.MapPath("XML/AdCenterPath.xml"));

        string ss = hiddenpermission.Value;
        hiddenpermission.Value = "";
        Ajax.Utility.RegisterTypeForAjax(typeof(adswap_publication));

        hiddenusername.Value = Session["Username"].ToString();
        if (Session["Username"] == null)
        {
            //Response.Redirect("login.aspx");
            Response.Write("<script>window.parent.location=\"login.aspx\";</script>");
            return;
        }
        else
        {
            username = Session["Username"].ToString();
            userid = Session["userid"].ToString();
        }

        if (!Page.IsPostBack)
        {
            btnExit.Attributes.Add("OnClick", "javascript:return exitclick();");
            btnCancel.Attributes.Add("OnClick", "javascript:return cancelClick();");
            btnQuery.Attributes.Add("OnClick", "javascript:return queryclick();");
            btnAdView.Attributes.Add("OnClick", "javascript:return ViewClick();");

            // btnUpload.Attributes.Add("OnClick", "javascript:return copyLocally();");
            // PubDate.Attributes.Add("Onchange", "javascript:return incorrectodate(PubDate);");
            // ddlPublication.Attributes.Add("OnChange", "javascript:return refreshfield();");
            // ddlCenter.Attributes.Add("OnChange", "javascript:return filledition();");
            // ddlEdition.Attributes.Add("OnChange", "javascript:return fillsupp();");

            PubDate.Attributes.Add("onfocus", "javascript:return changebackcolor(this);");
            ddlPublication.Attributes.Add("onfocus", "javascript:return changebackcolor(this);");
            //ddlCenter.Attributes.Add("onfocus", "javascript:return changebackcolor(this);");
            //ddlCenter.Attributes.Add("OnChange", "javascript:return filledition();");
            //ddlEdition.Attributes.Add("onfocus", "javascript:return changebackcolor(this);");
            ddlEdition.Attributes.Add("onfocus", "javascript:return filledition();");
            ddlEdition.Attributes.Add("OnChange", "javascript:return fillsupp();");
            ddlSupplement.Attributes.Add("onfocus", "javascript:return changebackcolor(this);");
            btnSend.Attributes.Add("onclick", "javascript:return sendtocenters();");
            //btnCopy.Attributes.Add("onclick", "javascript:return copy_previousdate_advt();");

            btnrevert.Attributes.Add("onclick", "javascript:return adswaprevert();"); 
            PubDate.Attributes.Add("OnChange", "javascript:return checkdate(this);");
            disable();
            addpubcode();
            addcentercode();
            addeditioncode();
            addsecpubcode();
            adtypedata(hiddencompcode.Value);

            pubdate1 = DateTime.Today.AddDays(1).ToShortDateString();

            string dateformat = Session["dateformat"].ToString();

            string month;
            string day;
            DateTime dt = DateTime.Now.AddDays(1);
            int year = Convert.ToInt32(dt.Year);
            if (Convert.ToString(dt.Month).Length == 1)
                month = "0" + Convert.ToString(dt.Month);
            else
                month = Convert.ToString(dt.Month);
            if (Convert.ToString(dt.Day).Length == 1)
                day = "0" + Convert.ToString(dt.Day);
            else
                day = Convert.ToString(dt.Day);

            if (Session["dateformat"].ToString() == "dd/mm/yyyy")
            {
                PubDate.Text = day + "/" + month + "/" + year;
            }
            else if (Session["dateformat"].ToString() == "yyyy/mm/dd")
            {
                PubDate.Text = year + "/" + month + "/" + day;
            }
            else
            {
                PubDate.Text = month + "/" + day + "/" + year;
            }

            //ddlPublication.SelectedIndex = 1;
            //ddlCenter.SelectedIndex = 1;            
            if (btnExit.Enabled == false)
                btnExit.ImageUrl = objDataSetbu.Tables[1].Rows[0].ItemArray[0].ToString();
            if (btnQuery.Enabled == false)
                btnQuery.ImageUrl = objDataSetbu.Tables[1].Rows[0].ItemArray[1].ToString();
            if (btnCancel.Enabled == false)
                btnCancel.ImageUrl = objDataSetbu.Tables[1].Rows[0].ItemArray[2].ToString();
        }

        Label1.Text = "";
        //***************bind centers************************
        /*DataSet ds_center = new DataSet();
        if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "sql")
        {
            //Layoutx.Classes.MaterialRename objcenters = new Layoutx.Classes.MaterialRename();
            //ds_center = objcenters.clsBindCenters();
        }
        else if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "orcl")
        {
            //Layoutx.OrclClass.MaterialRename objcenters = new Layoutx.OrclClass.MaterialRename();
            //ds_center = objcenters.clsBindCenters();
        }
        else
        {
            // Layoutx.mySqlclass.MaterialRename objcenters = new Layoutx.mySqlclass.MaterialRename();
            NewAdbooking.classmysql.adswap_publication objcenters = new NewAdbooking.classmysql.adswap_publication();
            ds_center = objcenters.clsBindCenters(Session["compcode"].ToString(), Session["userid"].ToString(),"","","");
        }
        if (ds_center.Tables[0].Rows.Count > 0)
        {
            SendGridView.DataSource = ds_center;
            SendGridView.DataBind();
        }*/
        //****************************************************
        DateTime da = DateTime.Now;
        string formname = "adswap_publication";
        DataSet dz = new DataSet();
        if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "sql")
        {
            NewAdbooking.Classes.Master checkform = new NewAdbooking.Classes.Master();
            dz = checkform.formpermission(hiddencompcode.Value, hiddenuserid.Value, formname);
        }
        else if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "orcl")
        {
            NewAdbooking.classesoracle.Master checkform = new NewAdbooking.classesoracle.Master();
            dz = checkform.formpermission(hiddencompcode.Value, hiddenuserid.Value, formname);
        }
        else
        {
            NewAdbooking.classmysql.Master checkform = new NewAdbooking.classmysql.Master();
            dz = checkform.formpermission(hiddencompcode.Value, hiddenuserid.Value, formname);
        }

        if (dz.Tables[0].Rows.Count > 0)
        {
            id = dz.Tables[0].Rows[0].ItemArray[0].ToString();
            if (id == "0" || id == "8")
            {
                hiddenpermission.Value = "zero";
                Response.Write("<script>alert('You are not authorised to see this form');</script>");
                return;
            }
        }
    }



    public void disable()
    {
        ddlPublication.Enabled = false;
        ddlCenter.Enabled = false;
        ddlEdition.Enabled = false;
        ddlSupplement.Enabled = false;
        PubDate.Enabled = false;
        txtPage.Enabled = false;
        btnAdView.Enabled = false;
    }


    public void addpubcode()
    {
        DataSet ds = new DataSet();
        if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "sql")
        {
            //Layoutx.Classes.Master Pripubl = new Layoutx.Classes.Master();
            //ddlPublication.Items.Clear();
            ////DataSet ds = new DataSet();
            //ds = Pripubl.Pripubcode(Session["compcode"].ToString(), Session["userid"].ToString());
        }
        else if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "orcl")
        {
            //Layoutx.OrclClass.Master Pripubl = new Layoutx.OrclClass.Master();
            ////DataSet ds = new DataSet();
            //ds = Pripubl.Pripubcode(Session["compcode"].ToString(), Session["userid"].ToString());
        }
        else
        {
            NewAdbooking.classmysql.adswap_publication Pripubl = new NewAdbooking.classmysql.adswap_publication();
            ds= Pripubl.Pripubcode(Session["compcode"].ToString(), Session["userid"].ToString());
            //Layoutx.mySqlclass.Master Pripubl = new Layoutx.mySqlclass.Master();
            //ds = Pripubl.Pripubcode(Session["compcode"].ToString(), Session["userid"].ToString());
        }
        int i;
        ListItem li1;
        li1 = new ListItem();
        li1.Text = "--Select Publ Code--";
        li1.Value = "0";//objDataSet.Tables[0].Rows[i].ItemArray[0].ToString();
        li1.Selected = true;
        ddlPublication.Items.Clear();
        ddlPublication.Items.Add(li1);

        if (ds.Tables[0].Rows.Count > 0)
        {
            for (i = 0; i < ds.Tables[0].Rows.Count; i++)
            {
                ListItem li;
                li = new ListItem();
                li.Text = ds.Tables[0].Rows[i].ItemArray[1].ToString();
                li.Value = ds.Tables[0].Rows[i].ItemArray[0].ToString();
                ddlPublication.Items.Add(li);
            }
        }
        ddlPublication.SelectedIndex = 1;
    }

    public void addcentercode()
    {
        DataSet ds = new DataSet();
        if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "sql")
        {
            //Layoutx.Classes.Master addCenter = new Layoutx.Classes.Master();
            //ddlCenter.Items.Clear();
            //ds = addCenter.centercode(Session["compcode"].ToString(), Session["userid"].ToString());
        }
        else if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "orcl")
        {
            //Layoutx.OrclClass.Master addCenter = new Layoutx.OrclClass.Master();
            //ds = addCenter.centercode(Session["compcode"].ToString(), Session["userid"].ToString());
        }
        else
        {
            NewAdbooking.classmysql.adswap_publication addCenter = new NewAdbooking.classmysql.adswap_publication();
            ds = addCenter.centercode(Session["compcode"].ToString(), Session["userid"].ToString());
            //Layoutx.mySqlclass.Master addCenter = new Layoutx.mySqlclass.Master();
            //ds = addCenter.centercode(Session["compcode"].ToString(), Session["userid"].ToString());
        }
        int i;
        ListItem li1;
        li1 = new ListItem();
        li1.Text = "--Select Center--";
        li1.Value = "0";//objDataSet.Tables[0].Rows[i].ItemArray[0].ToString();
        li1.Selected = true;
        ddlCenter.Items.Clear();
        ddlCenter.Items.Add(li1);
        if (ds.Tables[0].Rows.Count > 0)
        {
            for (i = 0; i < ds.Tables[0].Rows.Count; i++)
            {
                ListItem li;
                li = new ListItem();
                li.Text = ds.Tables[0].Rows[i].ItemArray[1].ToString();
                li.Value = ds.Tables[0].Rows[i].ItemArray[0].ToString();
                ddlCenter.Items.Add(li);
            }
            ddlCenter.SelectedIndex = 1;
        }
    }


    public void addeditioncode()
    {
        DataSet ds = new DataSet();
        if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "sql")
        {
            //Layoutx.Classes.Master addEdition = new Layoutx.Classes.Master();
            //ds = addEdition.editioncode(Session["compcode"].ToString(), Session["userid"].ToString());
        }
        else if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "orcl")
        {
           // Layoutx.OrclClass.Master addEdition = new Layoutx.OrclClass.Master();
           // ds = addEdition.editioncode(Session["compcode"].ToString(), Session["userid"].ToString());
        }
        else
        {
            NewAdbooking.classmysql.adswap_publication addEdition = new NewAdbooking.classmysql.adswap_publication();
            ds = addEdition.editioncode(Session["compcode"].ToString(), Session["userid"].ToString());

            //Layoutx.mySqlclass.Master addEdition = new Layoutx.mySqlclass.Master();
            //ds = addEdition.editioncode(Session["compcode"].ToString(), Session["userid"].ToString());
        }
        int i;
        ListItem li1;
        li1 = new ListItem();
        li1.Text = "--Select Edition--";
        li1.Value = "0";//objDataSet.Tables[0].Rows[i].ItemArray[0].ToString();
        li1.Selected = true;
        ddlEdition.Items.Clear();
        ddlEdition.Items.Add(li1);

        if (ds.Tables[0].Rows.Count > 0)
        {
            for (i = 0; i < ds.Tables[0].Rows.Count; i++)
            {
                ListItem li;
                li = new ListItem();
                li.Text = ds.Tables[0].Rows[i].ItemArray[1].ToString();
                li.Value = ds.Tables[0].Rows[i].ItemArray[0].ToString();
                ddlEdition.Items.Add(li);
            }
        }
    }

    public void addsecpubcode()
    {
        DataSet ds = new DataSet();
        if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "sql")
        {
            //Layoutx.Classes.Master addSecpub = new Layoutx.Classes.Master();
           // ds = addSecpub.secpubcode(Session["compcode"].ToString(), Session["userid"].ToString());
        }
        else if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "orcl")
        {
            //Layoutx.OrclClass.Master addSecpub = new Layoutx.OrclClass.Master();
            //ds = addSecpub.secpubcode(Session["compcode"].ToString(), Session["userid"].ToString());
        }
        else
        {
            NewAdbooking.classmysql.adswap_publication addSecpub = new NewAdbooking.classmysql.adswap_publication();
            ds = addSecpub.secpubcode(Session["compcode"].ToString(), Session["userid"].ToString());

            //Layoutx.mySqlclass.Master addSecpub = new Layoutx.mySqlclass.Master();
            //ds = addSecpub.secpubcode(Session["compcode"].ToString(), Session["userid"].ToString());
        }
        int i;
        ListItem li1;
        li1 = new ListItem();
        li1.Text = "--Select Supplement--";
        li1.Value = "0";//objDataSet.Tables[0].Rows[i].ItemArray[0].ToString();
        li1.Selected = true;
        ddlSupplement.Items.Clear();
        ddlSupplement.Items.Add(li1);
        if (ds.Tables[0].Rows.Count > 0)
        {
            for (i = 0; i < ds.Tables[0].Rows.Count; i++)
            {
                ListItem li;
                li = new ListItem();
                li.Text = ds.Tables[0].Rows[i].ItemArray[1].ToString();
                li.Value = ds.Tables[0].Rows[i].ItemArray[0].ToString();
                ddlSupplement.Items.Add(li);
            }
        }
    }


    protected void btnAdView_Click(object sender, EventArgs e)
    {
        showaddetails();
        clsBindCentersbtnclick();
    }

    public void showaddetails()
    {
        if (PubDate.Text == "")
        {
            ScriptManager.RegisterStartupScript(this.Page, this.GetType(), Guid.NewGuid().ToString(), "alert('Select Date');", true);
            // ScriptManager.SetFocus(PubDate);
            PubDate.Focus();
            return;
        }
        if (drpadtype.SelectedIndex == 0)
        {
            ScriptManager.RegisterStartupScript(this.Page, this.GetType(), Guid.NewGuid().ToString(), "alert('Select Ad Type');", true);
            drpadtype.Focus();
            btnAdView.Enabled = true;
            return;
        }

        if (ddlPublication.SelectedIndex == 0)
        {
            ScriptManager.RegisterStartupScript(this.Page, this.GetType(), Guid.NewGuid().ToString(), "alert('Select Publication');", true);
            ddlPublication.Focus();
            btnAdView.Enabled = true;
            return;
        }

        if (ddlCenter.SelectedIndex == 0)
        {
            ScriptManager.RegisterStartupScript(this.Page, this.GetType(), Guid.NewGuid().ToString(), "alert('Select Center');", true);
            ddlCenter.Focus();
            btnAdView.Enabled = true;
            return;
        }
        if (ddlEdition.SelectedIndex == 0)
        {
            ScriptManager.RegisterStartupScript(this.Page, this.GetType(), Guid.NewGuid().ToString(), "alert('Select Edition');", true);
            ddlEdition.Focus();
            btnAdView.Enabled = true;
            return;
        }

        if (ddlSupplement.SelectedIndex == 0)
        {
            ScriptManager.RegisterStartupScript(this.Page, this.GetType(), Guid.NewGuid().ToString(), "alert('Select Supplement');", true);
            ddlEdition.Focus();
            btnAdView.Enabled = true;
            return;
        }
        //***************************************************
        string month;
        string day;
        string year;
        string curdate;
        if (PubDate.Text == "")
            return;

        day = PubDate.Text.Split('/')[0];
        month = PubDate.Text.Split('/')[1];
        year = PubDate.Text.Split('/')[2];

        if (Session["dateformat"].ToString() == "dd/mm/yyyy")
        {
            curdate = day + month + year;
        }
        else if (Session["dateformat"].ToString() == "yyyy/mm/dd")
        {
            curdate = year + month + day;
        }
        else
        {
            curdate = month + day + year;
        }
        //********************************************************************* 
        String publication = ddlPublication.Text;
        String center = ddlCenter.Text;
        String edition = ddlEdition.Text;
        String supplement = ddlSupplement.Text;
        string ad_type = drpadtype.Text;

        hiddendateformat.Value = Session["dateformat"].ToString();
        DataSet ds = ViewAdBooking(hiddencompcode.Value, PubDate.Text, publication, center, edition, supplement, hiddendateformat.Value, txtPage.Text, ad_type);
        if (txtgridSize.Text == "" || txtgridSize.Text == "0")
            GridView1.PageSize = 150;
        else
            GridView1.PageSize = Convert.ToInt16(txtgridSize.Text);

        GridView1.DataSource = ds;
        GridView1.DataBind();

        if (GridView1.Rows.Count == 0)
        {
            // Response.Write("<Script>alert('The data is not available as per your selection');</Script>");
            ScriptManager.RegisterStartupScript(this.Page, this.GetType(), Guid.NewGuid().ToString(), "alert('The data is not available as per your selection');", true);
            // ddlEdition.Focus();
            btnAdView.Enabled = true;
            PubDate.Focus();
            return;
        }
        else
        {
            ds = ViewAdBooking(hiddencompcode.Value, PubDate.Text, publication, center, edition, supplement, hiddendateformat.Value, txtPage.Text, ad_type);
        }
           
        return;
    }


    //  Display booking Ad 
    public DataSet ViewAdBooking(string compcode, string pubdate, string pubcode, string centercode, string editioncode, string suppcode, string dateformat, string pageno, string ad_type)
    {
        //agenname=drpparent.Text.ToString();

        DataSet ds = new DataSet();
        if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "sql")
        {
            //Layoutx.Classes.MaterialRename bindAdBooking = new Layoutx.Classes.MaterialRename();
            //ds = bindAdBooking.clsViewBooking(compcode, pubdate, pubcode, centercode, editioncode, suppcode, dateformat, pageno);
        }
        else if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "orcl")
        {
            //Layoutx.OrclClass.MaterialRename bindAdBooking = new Layoutx.OrclClass.MaterialRename();
            //ds = bindAdBooking.clsViewBooking(compcode, pubdate, pubcode, centercode, editioncode, suppcode, dateformat, pageno);
        }
        else
        {
            NewAdbooking.classmysql.adswap_publication bindAdBooking = new NewAdbooking.classmysql.adswap_publication();
            ds = bindAdBooking.clsViewBooking(compcode, pubdate, pubcode, centercode, editioncode, suppcode, dateformat, pageno, ad_type);

            //Layoutx.mySqlclass.MaterialRename bindAdBooking = new Layoutx.mySqlclass.MaterialRename();
            //ds = bindAdBooking.clsViewBooking(compcode, pubdate, pubcode, centercode, editioncode, suppcode, dateformat, pageno);
        }
        return ds;
    }


    protected void GridView1_PageIndexChange(object sender, GridViewPageEventArgs e)
    {
        GridView1.PageIndex = e.NewPageIndex;
        btnAdView_Click(sender, e);
    }

    protected void GridView1_databound(object sender, GridViewRowEventArgs e)
    {
        /*if (e.Row.RowIndex != -1)
        {
            string strId = e.Row.Cells[12].Text;
            e.Row.Cells[0].Attributes.Add("onclick", "javascript:return getfilename(\"" + strId + "\")");
            j++;
        }*/
    }

 


    [Ajax.AjaxMethod(Ajax.HttpSessionStateRequirement.Read)]
    public DataSet bind_editioncode_dt(string pubdate, string centercode, string userid, string pubcode)
    {
        DataSet ds = new DataSet();
        if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "sql")
        {
            //Layoutx.Classes.Master addEdition = new Layoutx.Classes.Master();
           // ds = addEdition.editioncodes(centercode, userid, pubcode);
        }
        else if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "orcl")
        {
            //Layoutx.OrclClass.Master addEdition = new Layoutx.OrclClass.Master();
            //ds = addEdition.prefeditioncodes(centercode, userid, pubcode);
            //ds = addEdition.editioncodes_dt(pubdate, centercode, userid, pubcode, Session["dateformat"].ToString());
        }
        else
        {
            NewAdbooking.classmysql.adswap_publication addEdition = new NewAdbooking.classmysql.adswap_publication();
            ds = addEdition.editioncodes_dt(pubdate, centercode, userid, pubcode, Session["dateformat"].ToString());
            //Layoutx.mySqlclass.Master addEdition = new Layoutx.mySqlclass.Master();
            //ds = addEdition.editioncodes_dt(pubdate, centercode, userid, pubcode, Session["dateformat"].ToString());
        }
        return ds;
    }


    [Ajax.AjaxMethod]
    public DataSet bind_secpubcode(string compcode, string userid, string editioncode)
    {
        DataSet ds = new DataSet();
        if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "sql")
        {
            //Layoutx.Classes.Master addSecpub = new Layoutx.Classes.Master();
            //ds = addSecpub.secpubcodes(compcode, userid, editioncode);
        }
        else if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "orcl")
        {
           // Layoutx.OrclClass.Master addSecpub = new Layoutx.OrclClass.Master();
            //ds = addSecpub.secpubcodes(compcode, userid, editioncode);
        }
        else
        {

            NewAdbooking.classmysql.adswap_publication addSecpub = new NewAdbooking.classmysql.adswap_publication();
            ds = addSecpub.secpubcodes(compcode, userid, editioncode);

            //Layoutx.mySqlclass.Master addSecpub = new Layoutx.mySqlclass.Master();
            //ds = addSecpub.secpubcodes(compcode, userid, editioncode);
        }
        return ds;
    }



    // submit button

    //*****************************************************************
    protected void btnSend_Click(object sender, EventArgs e)
    {
        /*if (hiddenftpcenters.Value == "")
            return;
        string month;
        string day;
        string year;
        string curdate;
        if (PubDate.Text == "")
            return;

        day = PubDate.Text.Split('/')[0];
        month = PubDate.Text.Split('/')[1];
        year = PubDate.Text.Split('/')[2];
        if (Session["dateformat"].ToString() == "dd/mm/yyyy")
            curdate = day + month + year;
        else if (Session["dateformat"].ToString() == "yyyy/mm/dd")
            curdate = year + month + day;
        else
            curdate = month + day + year;

        string fname = Request.Form["RadioButton1"];
        string[] ftpcent = hiddenftpcenters.Value.Split('#');

        for (int i = 0; i < GridView1.Rows.Count; i++)
        {
            //if (fname == GridView1.Rows[i].Cells[12].Text)
            //{

           //bool isSelected = (GridView1.Rows[i].Cells[0].Controls[0] as CheckBox).Checked;
           //if (isSelected)
           // {
           //     string idnum = GridView1.Rows[i].Cells[1].Text;
           //     string insnum = GridView1.Rows[i].Cells[11].Text;
           //     string insertid = GridView1.Rows[i].Cells[14].Text;
           //     // GridViewRow row = SendGridView.Rows[i];
           //     // bool isChecked = ((CheckBox)row.FindControl("CheckBox1")).Checked;
           //     for (int k = 0; k < ftpcent.Length; k++)
           //     {
           //         DataSet ds_1 = new DataSet();
           //         //ds_1 = chkmaterial_transmit(fname, ftpcent[k], PubDate.Text, hiddendateformat.Value);
           //         //if (ds_1.Tables[0].Rows.Count == 0)
           //         //    material_transmit(fname, ftpcent[k], PubDate.Text, hiddendateformat.Value);
           //     }
           //     Response.Write("<script>alert('File is submitted for FTP');</script>");
           //     return;
           // }
           // else
           // {

           // }
        }*/
    }

    [Ajax.AjaxMethod(Ajax.HttpSessionStateRequirement.Read)]
    public DataSet swaptransferdata(string compcode, string insertdate, string booking_id, string booking_inserid, string pripub, string bkfor, string editionc, string secpubc, string pubtypec, string userid, string bk_allbackup, string PSWAP_TYPE, string extra1, string extra2, string extra3)
    {
        DataSet ds = new DataSet();
        if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "sql")
        {
            //Layoutx.Classes.Master addSecpub = new Layoutx.Classes.Master();
            //ds = addSecpub.secpubcodes(compcode, userid, editioncode);
        }
        else if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "orcl")
        {
            // Layoutx.OrclClass.Master addSecpub = new Layoutx.OrclClass.Master();
            //ds = addSecpub.secpubcodes(compcode, userid, editioncode);
        }
        else
        {

            NewAdbooking.classmysql.adswap_publication addSecpub = new NewAdbooking.classmysql.adswap_publication();
            ds = addSecpub.swaptransferdata(compcode, insertdate, booking_id, booking_inserid, pripub, bkfor, editionc, secpubc, pubtypec, userid, bk_allbackup, PSWAP_TYPE, extra1, extra2, extra3);

            //Layoutx.mySqlclass.Master addSecpub = new Layoutx.mySqlclass.Master();
            //ds = addSecpub.secpubcodes(compcode, userid, editioncode);
        }
        return ds;
    }




    public DataSet clsBindCentersdata(string compcode, string userid, string publication, string center, string extra3)
    {
        DataSet ds_center = new DataSet();
        if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "sql")
        {
            //Layoutx.Classes.MaterialRename objcenters = new Layoutx.Classes.MaterialRename();
            //ds_center = objcenters.clsBindCenters();
        }
        else if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "orcl")
        {
            //Layoutx.OrclClass.MaterialRename objcenters = new Layoutx.OrclClass.MaterialRename();
            //ds_center = objcenters.clsBindCenters();
        }
        else
        {
            // Layoutx.mySqlclass.MaterialRename objcenters = new Layoutx.mySqlclass.MaterialRename();
            NewAdbooking.classmysql.adswap_publication objcenters = new NewAdbooking.classmysql.adswap_publication();
            ds_center = objcenters.clsBindCenters(Session["compcode"].ToString(), Session["userid"].ToString(), publication, center, "");
        }
        /*if (ds_center.Tables[0].Rows.Count > 0)
        {
            SendGridView.DataSource = ds_center;
            SendGridView.DataBind();
        }*/
        return ds_center;

    }



    public void clsBindCentersbtnclick()
    {
        String center = ddlCenter.Text;
        String publication = ddlPublication.Text;
        DataSet ds_center1 = clsBindCentersdata(Session["compcode"].ToString(), Session["userid"].ToString(), publication, center, "");

        if (ds_center1.Tables[0].Rows.Count > 0)
        {
            SendGridView.DataSource = null;
            SendGridView.DataBind();
        }

        SendGridView.DataSource = ds_center1;
        SendGridView.DataBind();

        return;
    }


    public void adtypedata(string compcode)
    {
        DataSet ds = new DataSet();
        if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "sql")
        {
            NewAdbooking.Classes.CombinationMaster bind = new NewAdbooking.Classes.CombinationMaster();

            ds = bind.adtypbind(compcode);

        }

        else
            if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "orcl")
            {
                NewAdbooking.classesoracle.CombinationMaster bind = new NewAdbooking.classesoracle.CombinationMaster();

                ds = bind.adtypbind(compcode);
            }
            else
            {
                NewAdbooking.classmysql.CombinationMaster bind = new NewAdbooking.classmysql.CombinationMaster();

                ds = bind.adtypbind(compcode);

            }

        int i;
        ListItem li1;

        li1 = new ListItem();
        drpadtype.Items.Clear();
        li1.Text = "Select Ad Type";
        li1.Value = "0";
        li1.Selected = true;
        drpadtype.Items.Add(li1);

        for (i = 0; i < ds.Tables[0].Rows.Count; i++)
        {
            ListItem li;
            li = new ListItem();
            li.Value = ds.Tables[0].Rows[i].ItemArray[0].ToString();
            li.Text = ds.Tables[0].Rows[i].ItemArray[1].ToString();
            drpadtype.Items.Add(li);


        }

    }
    protected void drpadtype_SelectedIndexChanged(object sender, EventArgs e)
    {
        //bindcategory(Session["compcode"].ToString(), drpadtype.SelectedValue, "0");
    }


 
}
