using System;
using System.Data;
using System.Configuration;
using System.Collections;
using System.Web;
using System.Web.Security;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.HtmlControls;
using System.Data.SqlClient;
using System.Text.RegularExpressions;

/*using iTextSharp.text;*/
using System.IO;
using System.Data.OracleClient;
using iTextSharp.text.pdf;
using System.Drawing.Printing;
//using System.Diagnostics.Design;
using System.Diagnostics;
using iTextSharp.text.pdf.wmf;
using System.Web.UI.WebControls;
using System.Text;


public partial class booking_import_data : System.Web.UI.Page
{

    static string YMDToMDY(string input)
    {
        //System.Text.RegularExpressions Regex = new System.Text.RegularExpressions();
        return Regex.Replace(input,
            "\\b(?<year>\\d{2,4})/(?<month>\\d{1,2})/(?<day>\\d{1,2})\\b",
            "${month}/${day}/${year}");
    }
    static string DMYToMDY(string input)
    {
        //System.Text.RegularExpressions Regex = new SystemText.RegularExpressions();
        return Regex.Replace(input,
            "\\b(?<day>\\d{1,2})/(?<month>\\d{1,2})/(?<year>\\d{2,4})\\b",
            "${month}/${day}/${year}");
    }


    int j = 0;
    int z = 0;
    static int alpha;
    string checkboxname, compcode, userid, formname;
    static string saveormodify, chkquery, opendivsign;
    static DataSet globda = new DataSet();

    static int fpnl;
    static int FlagStatus;
    string valuee = "";
    public static string check = "";
    static string gcombinationcode = "";
    static string gadtype = "";
    static string gpaccode = "";
    static string gcombincode = "";
    static string galias = "";
    static string geditiontype = "";
    string sau = "";
    int TotalColSpan = 0, ColSpan1 = 0, ColSpan2 = 0;
    double col_sp = 0;

    StringBuilder TBL = new StringBuilder();
    StringBuilder head = new StringBuilder();
    protected void Page_Load(object sender, EventArgs e)
    {

        // Put user code to initialize the page here
        j = 0;
        z = 0;
        Response.Expires = -1;
        if (Session["compcode"] != null)
        {
            hiddendateformat.Value = Session["dateformat"].ToString();
            hiddencompcode.Value = Session["compcode"].ToString();
            //hiddenuserid.Value = Session["userid"].ToString();
            hiddenauto.Value = Session["autogenerated"].ToString();
            compcode = hiddencompcode.Value;
            userid = hiddenuserid.Value;
            //hiddenusername.Value = Session["Username"].ToString();
            gcombinationcode = hiddengcomcode.Value;
            gadtype = hiddengadtype.Value;
            gpaccode = hiddengpackcode.Value;
            gcombincode = hiddengcombncode.Value;
            galias = hiddengalias.Value;
            geditiontype = hiddengeditiontype.Value;
        }
        else
        {
            Response.Write("<script>alert(\"Your Session Has Been Expired\");window.close();</script>");
            return;
        }

        DataSet ds = new DataSet();
        // Read in the XML file
        ds.ReadXml(Server.MapPath("XML/booking_import_data.xml"));

        lblpubcenter.Text = ds.Tables[0].Rows[0].ItemArray[0].ToString();
        lbladtype.Text = ds.Tables[0].Rows[0].ItemArray[1].ToString();
        lblpublication.Text = ds.Tables[0].Rows[0].ItemArray[2].ToString();
        lbDateFrom.Text = ds.Tables[0].Rows[0].ItemArray[3].ToString();
        lbToDate.Text = ds.Tables[0].Rows[0].ItemArray[4].ToString();
        BtnRun.Text = ds.Tables[0].Rows[0].ItemArray[5].ToString();

        formname = "booking_import_data";
        Ajax.Utility.RegisterTypeForAjax(typeof(booking_import_data));


        if (!Page.IsPostBack)
        {
            fillPubCenter();
            adtypedata(compcode);
            fillPublication(compcode);
        }


    }


    private void fillPublication(string compcode)
    {
        DataSet ds;
        drppublication.Items.Clear();
        if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "sql")
        {

            NewAdbooking.Classes.login logindetail = new NewAdbooking.Classes.login();

            ds = logindetail.getPubCenter();
        }
        else if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "orcl")
        {
            NewAdbooking.classesoracle.login logindetail = new NewAdbooking.classesoracle.login();

            ds = logindetail.getPubCenter();

        }
        else
        {
            NewAdbooking.classmysql.EditorMaster PubName = new NewAdbooking.classmysql.EditorMaster();
            ds = PubName.Pub(hiddencompcode.Value);
        }

        ListItem li1;
        li1 = new ListItem();
        li1.Text = "---Select Publication---";
        li1.Value = "0";
        li1.Selected = true;
        drppublication.Items.Add(li1);
        string[] drptext;
        int i;
        for (i = 0; i < ds.Tables[0].Rows.Count; i++)
        {
            ListItem li;
            li = new ListItem();
            if (ds.Tables[0].Rows[i].ItemArray[1].ToString().IndexOf("(") > 0)
            {
                li.Text = ds.Tables[0].Rows[i].ItemArray[0].ToString();
                // li.Text = drptext[0];
            }
            else
            {
                li.Text = ds.Tables[0].Rows[i].ItemArray[0].ToString();
            }
            li.Value = ds.Tables[0].Rows[i].ItemArray[1].ToString();
            drppublication.Items.Add(li);
        }

    }



    private void fillPubCenter()
    {
        DataSet ds;
        drppubcenter.Items.Clear();
        if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "sql")
        {

            NewAdbooking.Classes.login logindetail = new NewAdbooking.Classes.login();

            ds = logindetail.getPubCenter();
        }
        else if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "orcl")
        {
            NewAdbooking.classesoracle.login logindetail = new NewAdbooking.classesoracle.login();

            ds = logindetail.getPubCenter();

        }
        else
        {
            NewAdbooking.classmysql.login logindetail = new NewAdbooking.classmysql.login();
            ds = logindetail.getPubCenter();
        }

        ListItem li1;
        li1 = new ListItem();
        li1.Text = "Select Center";
        li1.Value = "0";
        li1.Selected = true;
        drppubcenter.Items.Add(li1);
        string[] drptext;
        int i;
        for (i = 0; i < ds.Tables[0].Rows.Count; i++)
        {
            ListItem li;
            li = new ListItem();
            if (ds.Tables[0].Rows[i].ItemArray[1].ToString().IndexOf("(") > 0)
            {
                drptext = ds.Tables[0].Rows[i].ItemArray[1].ToString().Split('(');
                li.Text = drptext[0];
            }
            else
            {
                li.Text = ds.Tables[0].Rows[i].ItemArray[1].ToString();
            }
            li.Value = ds.Tables[0].Rows[i].ItemArray[0].ToString();
            drppubcenter.Items.Add(li);
        }

    }


    public void adtypedata(string compcode)
    {
        DataSet ds = new DataSet();
        if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "sql")
        {
            NewAdbooking.Classes.CombinationMaster bind = new NewAdbooking.Classes.CombinationMaster();

            ds = bind.adtypbind(compcode);

        }

        else
            if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "orcl")
            {
                NewAdbooking.classesoracle.CombinationMaster bind = new NewAdbooking.classesoracle.CombinationMaster();

                ds = bind.adtypbind(compcode);
            }
            else
            {
                NewAdbooking.classmysql.CombinationMaster bind = new NewAdbooking.classmysql.CombinationMaster();

                ds = bind.adtypbind(compcode);

            }

        int i;
        ListItem li1;

        li1 = new ListItem();
        drpadtype.Items.Clear();
        li1.Text = "Select Ad Type";
        li1.Value = "0";
        li1.Selected = true;
        drpadtype.Items.Add(li1);

        for (i = 0; i < ds.Tables[0].Rows.Count; i++)
        {
            ListItem li;
            li = new ListItem();
            li.Value = ds.Tables[0].Rows[i].ItemArray[0].ToString();
            li.Text = ds.Tables[0].Rows[i].ItemArray[1].ToString();
            drpadtype.Items.Add(li);


        }

    }



    protected void drppubcenter_SelectedIndexChanged(object sender, EventArgs e)
    {
        //drpadtype.SelectedValue = "0";
    }
    protected void drpadtype_SelectedIndexChanged(object sender, EventArgs e)
    {
        //bindcategory(Session["compcode"].ToString(), drpadtype.SelectedValue, "0");
    }


    protected void BtnRun_Click(object sender, EventArgs e)
    {
        SqlDataAdapter da = new SqlDataAdapter();
        DataSet ds = new DataSet();
        if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "orcl")
        {

        }
        else if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "sql")
        {

        }
        else
        {
            string drppubcenterc = drppubcenter.SelectedValue;
            string drpadtypec = drpadtype.SelectedValue;
            string drppublicationc = drppublication.SelectedValue;
            string fromdate = txtfrmdate.Text;
            string todate = txttodate1.Text;
            string billtype = Txtdest.SelectedValue;
            string extra1 = ""; string extra2 = ""; string extra3 = ""; string extra4 = "";
            if (drppubcenterc == "0") { drppubcenterc = ""; }
            if (drpadtypec == "0") { drpadtypec = ""; }
            if (drppublicationc == "0") { drppublicationc = ""; }
            if (billtype == "0") { billtype = "I"; }

            //string procedureName = "ad_bill_data_tnie";
            string[] parameterValueArray = { Session["compcode"].ToString(), drppubcenterc, drpadtypec, drppublicationc, fromdate, todate, billtype, extra2, extra3, extra4 };
            //NewAdbooking.classmysql.CommonClass obj = new NewAdbooking.classmysql.CommonClass();
            //ds = obj.DynamicBindProcedure(procedureName, parameterValueArray);

            NewAdbooking.classmysql.bookingmaterialdata bind = new NewAdbooking.classmysql.bookingmaterialdata();
            ds = bind.booking_import_data_bind(Session["compcode"].ToString(), drppubcenterc, drpadtypec, drppublicationc, fromdate, todate, billtype, extra2, extra3, extra4);


        }
        string destination = "1";
        if (ds.Tables[0].Rows.Count == 0)
        {
            ScriptManager.RegisterClientScriptBlock(this, typeof(booking_import_data), "sa", "alert(\"searching criteria is not valid\");", true);
            return;
        }
        else
        {
            Session["frmdt"] = txtfrmdate.Text;
            Session["todt"] = txttodate1.Text;

            Session["statusad"] = ds;
            Session["prm_statusad"] = "destination~" + destination;
            Response.Redirect("booking_import_data_rpt.aspx");
        }






    }

    protected void BtnRun_Click_csv(object sender, EventArgs e)
    {
        SqlDataAdapter da = new SqlDataAdapter();
        DataSet ds = new DataSet();
        if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "orcl")
        {

        }
        else if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "sql")
        {

        }
        else
        {
            string drppubcenterc = drppubcenter.SelectedValue;
            string drpadtypec = drpadtype.SelectedValue;
            string drppublicationc = drppublication.SelectedValue;
            string fromdate = txtfrmdate.Text;
            string todate = txttodate1.Text;
            string billtype = Txtdest.SelectedValue;

            string extra1 = ""; string extra2 = ""; string extra3 = ""; string extra4 = "";
            if (drppubcenterc == "0") { drppubcenterc = ""; }
            if (drpadtypec == "0") { drpadtypec = ""; }
            if (drppublicationc == "0") { drppublicationc = ""; }
            if (billtype == "0") { billtype = "I"; }


            //string procedureName = "ad_bill_data_tnie";
            string[] parameterValueArray = { Session["compcode"].ToString(), drppubcenterc, drpadtypec, drppublicationc, fromdate, todate, billtype, extra2, extra3, extra4 };
            //NewAdbooking.classmysql.CommonClass obj = new NewAdbooking.classmysql.CommonClass();
            //ds = obj.DynamicBindProcedure(procedureName, parameterValueArray);
            NewAdbooking.classmysql.bookingmaterialdata bind = new NewAdbooking.classmysql.bookingmaterialdata();
            ds = bind.booking_import_data_bind(Session["compcode"].ToString(), drppubcenterc, drpadtypec, drppublicationc, fromdate, todate, billtype, extra2, extra3, extra4);

        }
        string destination = "csv";
        if (ds.Tables[0].Rows.Count == 0)
        {
            ScriptManager.RegisterClientScriptBlock(this, typeof(booking_import_data), "sa", "alert(\"searching criteria is not valid\");", true);
            return;
        }
        else
        {
            Session["frmdt"] = txtfrmdate.Text;
            Session["todt"] = txttodate1.Text;

            Session["statusad"] = ds;
            Session["prm_statusad"] = "destination~" + destination;
            Response.Redirect("booking_import_data_rpt.aspx");
        }






    }


    protected void BtnRun_Click_dps(object sender, EventArgs e)
    {
        SqlDataAdapter da = new SqlDataAdapter();
        DataSet ds = new DataSet();
        if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "orcl")
        {

        }
        else if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "sql")
        {

        }
        else
        {
            string drppubcenterc = drppubcenter.SelectedValue;
            string drpadtypec = drpadtype.SelectedValue;
            string drppublicationc = drppublication.SelectedValue;
            string fromdate = txtfrmdate.Text;
            string todate = txttodate1.Text;
            string billtype = Txtdest.SelectedValue;

            string extra1 = ""; string extra2 = ""; string extra3 = ""; string extra4 = "";
            if (drppubcenterc == "0") { drppubcenterc = ""; }
            if (drpadtypec == "0") { drpadtypec = ""; }
            if (drppublicationc == "0") { drppublicationc = ""; }
            if (billtype == "0") { billtype = "I"; }

            //string procedureName = "booking_data_upload_det";
            string[] parameterValueArray = { Session["compcode"].ToString(), drppubcenterc, drpadtypec, drppublicationc, fromdate, todate, billtype, extra2, extra3, extra4 };
            //NewAdbooking.classmysql.CommonClass obj = new NewAdbooking.classmysql.CommonClass();
            //ds = obj.DynamicBindProcedure(procedureName, parameterValueArray);

            NewAdbooking.classmysql.bookingmaterialdata bind = new NewAdbooking.classmysql.bookingmaterialdata();
            ds = bind.booking_import_data_dpsbind(Session["compcode"].ToString(), drppubcenterc, drpadtypec, drppublicationc, fromdate, todate, billtype, extra2, extra3, extra4);


        }
        string destination = "csvd";
        if (ds.Tables[0].Rows.Count == 0)
        {
            ScriptManager.RegisterClientScriptBlock(this, typeof(booking_import_data), "sa", "alert(\"searching criteria is not valid\");", true);
            return;
        }
        else
        {
            Session["frmdt"] = txtfrmdate.Text;
            Session["todt"] = txttodate1.Text;

            Session["statusad"] = ds;
            Session["prm_statusad"] = "destination~" + destination;
            Response.Redirect("booking_import_data_rpt.aspx");
        }






    }
}

