using System;
using System.Data;
using System.Configuration;
using System.Collections;
using System.Web;
using System.Web.Security;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.HtmlControls;

public partial class loginAdSession : System.Web.UI.Page
{
    protected void Page_Load(object sender, EventArgs e)
    {
        Response.Expires = -1;

        string flag = "0";
        string username = Request.QueryString["username"].ToString();
        string password = Request.QueryString["password"].ToString();
        string qbc = Request.QueryString["qbc"].ToString();
        
        DataSet ds = new DataSet();
        if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "sql")
        {
            NewAdbooking.Classes.loginAdmin logindetail = new NewAdbooking.Classes.loginAdmin();
            ds = logindetail.chklogin(username, password);
        }
        else
            if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "orcl")
            {
                 NewAdbooking.classesoracle .loginAdmin logindetail = new NewAdbooking.classesoracle.loginAdmin();
            ds = logindetail.chklogin(username, password);
            }
        else
        {
            NewAdbooking.classmysql.loginAdmin logindetail = new NewAdbooking.classmysql.loginAdmin();
            ds = logindetail.chklogin(username, password);
        }
        if (ds.Tables[0].Rows.Count > 0)
        {
            flag = "1";
            Session["revenue"] = qbc;
            Session["Username"] = ds.Tables[0].Rows[0].ItemArray[0].ToString();
            Session["comp_name"] = ds.Tables[0].Rows[0].ItemArray[7].ToString();
            Session["userid"] = ds.Tables[0].Rows[0].ItemArray[2].ToString();
            Session["compcode"] = ds.Tables[0].Rows[0].ItemArray[4].ToString();
           
            //UserLabel.Value = Session["Username"].ToString();
            if (ds.Tables[1].Rows.Count > 0)
            {
                Session["dateformat"] = ds.Tables[1].Rows[0].ItemArray[3].ToString();
                Session["autogenerated"] = ds.Tables[1].Rows[0].ItemArray[1].ToString();
                Session["currency"] = ds.Tables[1].Rows[0].ItemArray[2].ToString();
                Session["ratecode"] = ds.Tables[1].Rows[0].ItemArray[0].ToString();
                Session["solorate"] = ds.Tables[1].Rows[0].ItemArray[4].ToString();
                Session["decimal"] = ds.Tables[1].Rows[0].ItemArray[5].ToString();
                Session["breakup"] = ds.Tables[1].Rows[0].ItemArray[6].ToString();
                Session["bwcode"] = ds.Tables[1].Rows[0].ItemArray[7].ToString();
                Session["uom"] = ds.Tables[1].Rows[0].ItemArray[8].ToString();
                Session["rostatus"] = ds.Tables[1].Rows[0].ItemArray[9].ToString();
                Session["tfn"] = ds.Tables[1].Rows[0].ItemArray[10].ToString();
                Session["insertsbreakup"] = ds.Tables[1].Rows[0].ItemArray[11].ToString();
                Session["premtype"] = ds.Tables[1].Rows[0].ItemArray[12].ToString();
                Session["dealtype"] = ds.Tables[1].Rows[0].ItemArray[13].ToString();
                Session["prefix"] = ds.Tables[1].Rows[0].ItemArray[14].ToString();
                Session["suffix"] = ds.Tables[1].Rows[0].ItemArray[15].ToString();
                Session["financestatus"] = ds.Tables[1].Rows[0].ItemArray[16].ToString();
                Session["voucherst"] = ds.Tables[1].Rows[0].ItemArray[17].ToString();
                Session["roadcat"] = ds.Tables[1].Rows[0].ItemArray[18].ToString();
                Session["rodatetime"] = ds.Tables[1].Rows[0].ItemArray[19].ToString();
                Session["spacearea"] = ds.Tables[1].Rows[0].ItemArray[20].ToString();
                Session["vat"] = ds.Tables[1].Rows[0].ItemArray[21].ToString();
                Session["bookstat"] = ds.Tables[1].Rows[0].ItemArray[22].ToString();
                Session["cioid"] = ds.Tables[1].Rows[0].ItemArray[23].ToString();
                Session["Receipt_no"] = ds.Tables[1].Rows[0].ItemArray[24].ToString();
                Session["agencyratecode"] = ds.Tables[1].Rows[0].ItemArray[27].ToString();
            }
            if (ds.Tables[2].Rows.Count > 0)
            {
                Session["userhome"] = ds.Tables[2].Rows[0].ItemArray[0].ToString();
                Session["Admin"] = ds.Tables[2].Rows[0].ItemArray[1].ToString();
               
            }

            //Response.Redirect("EnterPage.aspx");
            //Response.Redirect("Adsize_master.aspx");
            //Response.Redirect("Agent_master.aspx");
            //Response.Redirect("Revenue_master.aspx");
            //Response.Redirect("CombinationMaster.aspx");
            //Response.Redirect("Bullet_master.aspx");
            //Response.Redirect("Premium_typ_master.aspx");
            //Response.Redirect("RepMast.aspx");
            //Response.Redirect("Pageparametermaster.aspx");
            //Response.Redirect("Adv_booking.aspx");
            //Response.Redirect("UOM.aspx");
            //Response.Redirect("Currencymaster.aspx");
            //Response.Redirect("Contractmaster.aspx");
            //Response.Redirect("Default.aspx");
            //Response.Redirect("ProductMaster.aspx");
            //Response.Redirect("Clientrolemaster.aspx");
            // Response.Redirect("AgencyTypeMaster.aspx");
            //Response.Redirect("ClientMaster.aspx");
        }
        else
        {
            flag = "0";
        }
        // return ;

        Response.Write(flag);
        Response.End();
    }
}