using System;
using System.Data;
using System.Configuration;
using System.Collections;
using System.Web;
using System.Web.Security;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.HtmlControls;

public partial class PubCatRef : System.Web.UI.Page
{
    protected void Page_Load(object sender, EventArgs e)
    {
        Response.Expires = -1;

        if (Session["compcode"] != null)
        {
            hiddencompcode.Value = Session["compcode"].ToString();
            //hiddenuserid.Value = Session["userid"].ToString();
            //hiddenauto.Value = Session["autogenerated"].ToString();
            //hiddensolorate.Value = Session["solorate"].ToString();
        }

        else
        {
           
            Response.Write("<script>window.parent.location=\"login.aspx\";</script>");
            return;

        }

        Ajax.Utility.RegisterTypeForAjax(typeof(PubCatRef));
        //***********************************************************************//
        //*****************Code For Read the data from xml File******************//
        //*******************************For The Button**************************//
        //***********************************************************************/
        DataSet objDataSetbu = new DataSet();
        objDataSetbu.ReadXml(Server.MapPath("XML/button.xml"));
        btnNew.ImageUrl = objDataSetbu.Tables[0].Rows[0].ItemArray[0].ToString();
        btnSave.ImageUrl = objDataSetbu.Tables[0].Rows[0].ItemArray[1].ToString();
        btnModify.ImageUrl = objDataSetbu.Tables[0].Rows[0].ItemArray[2].ToString();
        btnQuery.ImageUrl = objDataSetbu.Tables[0].Rows[0].ItemArray[3].ToString();
        btnExecute.ImageUrl = objDataSetbu.Tables[0].Rows[0].ItemArray[4].ToString();
        btnCancel.ImageUrl = objDataSetbu.Tables[0].Rows[0].ItemArray[5].ToString();
        btnfirst.ImageUrl = objDataSetbu.Tables[0].Rows[0].ItemArray[6].ToString();
        btnprevious.ImageUrl = objDataSetbu.Tables[0].Rows[0].ItemArray[7].ToString();
        btnnext.ImageUrl = objDataSetbu.Tables[0].Rows[0].ItemArray[8].ToString();
        btnlast.ImageUrl = objDataSetbu.Tables[0].Rows[0].ItemArray[9].ToString();
        btnDelete.ImageUrl = objDataSetbu.Tables[0].Rows[0].ItemArray[10].ToString();
        btnExit.ImageUrl = objDataSetbu.Tables[0].Rows[0].ItemArray[11].ToString();

        //********************************For Label****************************************/
        DataSet ds = new DataSet();
        ds.ReadXml(Server.MapPath("XML/PubCatRef.xml"));

        lblpub.Text = ds.Tables[0].Rows[0].ItemArray[0].ToString();
        lbcat.Text = ds.Tables[0].Rows[0].ItemArray[1].ToString();
        lbsubcat.Text = ds.Tables[0].Rows[0].ItemArray[2].ToString();
        lbname.Text = ds.Tables[0].Rows[0].ItemArray[3].ToString();

        btnNew.Enabled = true;
        btnSave.Enabled = false;
        btnModify.Enabled = false;
        btnDelete.Enabled = false;
        btnQuery.Enabled = true;
        btnExecute.Enabled = false;
        btnCancel.Enabled = true;
        btnfirst.Enabled = false;
        btnprevious.Enabled = false;
        btnnext.Enabled = false;
        btnlast.Enabled = false;
        btnExit.Enabled = true;

        drpPubName.Enabled = false;
        drpadcategory.Enabled = false;
        drpadvcatcode.Enabled = false;
        txtname.Enabled = false;

        if (btnNew.Enabled == false)
            btnNew.ImageUrl = objDataSetbu.Tables[1].Rows[0].ItemArray[0].ToString();
        if (btnSave.Enabled == false)
            btnSave.ImageUrl = objDataSetbu.Tables[1].Rows[0].ItemArray[1].ToString();
        if (btnModify.Enabled == false)
            btnModify.ImageUrl = objDataSetbu.Tables[1].Rows[0].ItemArray[2].ToString();
        if (btnQuery.Enabled == false)
            btnQuery.ImageUrl = objDataSetbu.Tables[1].Rows[0].ItemArray[3].ToString();
        if (btnExecute.Enabled == false)
            btnExecute.ImageUrl = objDataSetbu.Tables[1].Rows[0].ItemArray[4].ToString();
        if (btnCancel.Enabled == false)
            btnCancel.ImageUrl = objDataSetbu.Tables[1].Rows[0].ItemArray[5].ToString();
        if (btnfirst.Enabled == false)
            btnfirst.ImageUrl = objDataSetbu.Tables[1].Rows[0].ItemArray[6].ToString();
        if (btnprevious.Enabled == false)
            btnprevious.ImageUrl = objDataSetbu.Tables[1].Rows[0].ItemArray[7].ToString();
        if (btnnext.Enabled == false)
            btnnext.ImageUrl = objDataSetbu.Tables[1].Rows[0].ItemArray[8].ToString();
        if (btnlast.Enabled == false)
            btnlast.ImageUrl = objDataSetbu.Tables[1].Rows[0].ItemArray[9].ToString();
        if (btnDelete.Enabled == false)
            btnDelete.ImageUrl = objDataSetbu.Tables[1].Rows[0].ItemArray[10].ToString();
        if (btnExit.Enabled == false)
            btnExit.ImageUrl = objDataSetbu.Tables[1].Rows[0].ItemArray[11].ToString();
        btnNew.Focus();
        if (!Page.IsPostBack)
        {
            addPub();
            btnNew.Attributes.Add("OnClick", "javascript:return pubcatnewclick();");
            btnSave.Attributes.Add("OnClick", "javascript:return pubcatsaveclick();");
            //txtadcat3name.Attributes.Add("OnChange", "javascript:return autoornot();");
            btnModify.Attributes.Add("OnClick", "javascript:return pubcatmodifyclick();");
            btnQuery.Attributes.Add("OnClick", "javascript:return pubcatqueryclick();");
            btnExecute.Attributes.Add("OnClick", "javascript:return pubcatexecuteclick();");
            btnfirst.Attributes.Add("OnClick", "javascript:return pubcatfirstclick();");
            btnprevious.Attributes.Add("OnClick", "javascript:return pubcatpreviousclick();");
            btnnext.Attributes.Add("OnClick", "javascript:return pubcatnextclick();");
            btnlast.Attributes.Add("OnClick", "javascript:return pubcatlastclick();");
            btnExit.Attributes.Add("OnClick", "javascript:return pubcatexitclick();");
            btnDelete.Attributes.Add("OnClick", "javascript:return pubcatdeleteclick();");
            btnCancel.Attributes.Add("OnClick", "javascript:return pubcatcancelclick('PubCatRef');");
            drpadcategory.Attributes.Add("OnChange", "javascript:return fillAdCat2();");
            category1("CL0");
        }
    }

    public void category1(string adtype)
    {
        DataSet ds = new DataSet();

        //adtype = "CL0".ToString();
        if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "sql")
        {

            NewAdbooking.Classes.AdCat4 category = new NewAdbooking.Classes.AdCat4();

            ds = category.addcategoryname1("", Session["compcode"].ToString());
        }
        else if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "orcl")
        {
            NewAdbooking.classesoracle.AdCat4 category = new NewAdbooking.classesoracle.AdCat4();

            ds = category.addcategoryname1("", Session["compcode"].ToString());
        }

        else
        {
            NewAdbooking.classmysql.AdCat4 category = new NewAdbooking.classmysql.AdCat4();

            ds = category.addcategoryname1("");
        }
        ListItem li1;
        li1 = new ListItem();
        li1.Text = "-Select Add Category-";
        li1.Value = "0";
        li1.Selected = true;
        drpadcategory.Items.Add(li1);

        int i;
        for (i = 0; i < ds.Tables[0].Rows.Count; i++)
        {
            ListItem li;
            li = new ListItem();
            li.Text = ds.Tables[0].Rows[i].ItemArray[1].ToString();
            li.Value = ds.Tables[0].Rows[i].ItemArray[0].ToString();
            drpadcategory.Items.Add(li);


        }



    }
    //**********This is used to bind publication name***************//

    public void addPub()
    {
        DataSet ds = new DataSet();
        if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "sql")
        {
            NewAdbooking.Classes.EditorMaster PubName = new NewAdbooking.Classes.EditorMaster();
            ds = PubName.Pub(hiddencompcode.Value);
        }
        else if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "orcl")
        {
            NewAdbooking.classesoracle.EditorMaster PubName = new NewAdbooking.classesoracle.EditorMaster();
            ds = PubName.Pub(hiddencompcode.Value);
        }
        else
        {
            NewAdbooking.classmysql.EditorMaster PubName = new NewAdbooking.classmysql.EditorMaster();
            ds = PubName.Pub(hiddencompcode.Value);
        }
        ListItem li1;
        li1 = new ListItem();
        li1.Text = "---Select Publication---";
        li1.Value = "0";
        li1.Selected = true;
        drpPubName.Items.Add(li1);

        int i;
        for (i = 0; i < ds.Tables[0].Rows.Count; i++)
        {
            ListItem li;
            li = new ListItem();
            li.Value = ds.Tables[0].Rows[i].ItemArray[1].ToString();
            li.Text = ds.Tables[0].Rows[i].ItemArray[0].ToString();
            drpPubName.Items.Add(li);
        }
    }
     
    [Ajax.AjaxMethod(Ajax.HttpSessionStateRequirement.Read)]
    public DataSet fillCat2(string cat1)
    {
        DataSet ds = new DataSet();
        if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "sql")
        {
            NewAdbooking.Classes.AdCat4 category = new NewAdbooking.Classes.AdCat4();

            ds = category.addcategoryname2(cat1, Session["compcode"].ToString());
        }
        else if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "orcl")
        {
            NewAdbooking.classesoracle.AdCat4 category = new NewAdbooking.classesoracle.AdCat4();

            ds = category.addcategoryname2(cat1, Session["compcode"].ToString());
        }
        else
        {
            NewAdbooking.classmysql.AdCat4 category = new NewAdbooking.classmysql.AdCat4();

            ds = category.addcategoryname2(cat1, Session["compcode"].ToString());
        }
        return ds;
    }
[Ajax.AjaxMethod]
public DataSet chkname(string compcode,string pubname,string catname,string subcatname,string refname)
{
    DataSet ds = new DataSet();
    if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "sql")
    {
        NewAdbooking.Classes.pubcatref chk = new NewAdbooking.Classes.pubcatref();
        ds = chk.chkpubcatname(compcode, pubname, catname, subcatname, refname);
    }
    else if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "orcl")
    {
        NewAdbooking.classesoracle.pubcatref chk = new NewAdbooking.classesoracle.pubcatref();
        ds = chk.chkpubcatname(compcode, pubname, catname, subcatname, refname);

    }
    else
    {
        //NewAdbooking.classmysql.pubcatref chk = new NewAdbooking.classmysql.pubcatref();
        //ds = chk.chkpubcatname(compcode, pubname, catname, subcatname, refname);
    }
    return ds;
}
[Ajax.AjaxMethod]
public void pubcatsave(string compcode,string pubname,string catname,string subcatname,string refname)
{
    DataSet ds=new DataSet();
    if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "sql")
    {
        NewAdbooking.Classes.pubcatref insert = new NewAdbooking.Classes.pubcatref();
        ds = insert.savedata(compcode, pubname, catname, subcatname, refname);
    }
    else if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "orcl")
    {
        NewAdbooking.classesoracle.pubcatref insert = new NewAdbooking.classesoracle.pubcatref();
        ds = insert.savedata(compcode, pubname, catname, subcatname, refname);

    }
    else
    {
        //NewAdbooking.classmysql.pubcatref chk = new NewAdbooking.classmysql.pubcatref();
        //ds = chk.chkpubcatname(compcode, pubname, catname, subcatname, refname);
    }
}
[Ajax.AjaxMethod]
public void pubcatmodify(string compcode,string pubname,string catname,string subcatname,string refname)
{
    DataSet ds=new DataSet();
    if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "sql")
    {
        NewAdbooking.Classes.pubcatref modi = new NewAdbooking.Classes.pubcatref();
        ds = modi.updatepubcat(compcode, pubname, catname, subcatname, refname);
    }
    else if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "orcl")
    {
        NewAdbooking.classesoracle.pubcatref modi = new NewAdbooking.classesoracle.pubcatref();
        ds = modi.updatepubcat(compcode, pubname, catname, subcatname, refname);

    }
    else
    {
        //NewAdbooking.classmysql.pubcatref chk = new NewAdbooking.classmysql.pubcatref();
        //ds = chk.chkpubcatname(compcode, pubname, catname, subcatname, refname);
    }
}
[Ajax.AjaxMethod]
public DataSet pubcatexecute(string compcode,string pubname,string catname,string subcatname,string refname)
{
    DataSet ds=new DataSet();
     if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "sql")
    {
        NewAdbooking.Classes.pubcatref exe = new NewAdbooking.Classes.pubcatref();
        ds = exe.pubcatexecute(compcode, pubname, catname, subcatname, refname);
    }
    else if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "orcl")
    {
        NewAdbooking.classesoracle.pubcatref exe = new NewAdbooking.classesoracle.pubcatref();
        ds = exe.pubcatexecute(compcode, pubname, catname, subcatname, refname);

    }
    else
    {
        //NewAdbooking.classmysql.pubcatref chk = new NewAdbooking.classmysql.pubcatref();
        //ds = chk.chkpubcatname(compcode, pubname, catname, subcatname, refname);
    }
    return ds;
}
[Ajax.AjaxMethod]
public void pubcatdelete(string compcode,string pubname,string catname,string subcatname)
{
    DataSet ds=new DataSet();
     if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "sql")
    {
        NewAdbooking.Classes.pubcatref del = new NewAdbooking.Classes.pubcatref();
        ds = del.pubcatdelete(compcode, pubname, catname, subcatname);
    }
    else if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "orcl")
    {
        NewAdbooking.classesoracle.pubcatref del = new NewAdbooking.classesoracle.pubcatref();
        ds = del.pubcatdelete(compcode, pubname, catname, subcatname);

    }
    else
    {
        //NewAdbooking.classmysql.pubcatref chk = new NewAdbooking.classmysql.pubcatref();
        //ds = chk.chkpubcatname(compcode, pubname, catname, subcatname, refname);
    }
   // return ds;
}
}
