using System;
using System.Data;
using System.Configuration;
using System.Collections;
using System.Web;
using System.Web.Security;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.HtmlControls;

public partial class RateGroupMaster : System.Web.UI.Page
{
    protected void Page_Load(object sender, System.EventArgs e)
    {
        Response.Expires = -1;
        if (Session["compcode"] != null)
        {
            hiddencompcode.Value = Session["compcode"].ToString();
            hiddenuserid.Value = Session["userid"].ToString();
            hiddendateformat.Value = Session["dateformat"].ToString();
            hiddenauto.Value = Session["autogenerated"].ToString();

        }
        else
        {
            //Response.Redirect("login.aspx");
            Response.Write("<script>window.parent.location=\"login.aspx\";</script>");
            return;
        }



       /* if (Session["Username"] == null)
        {
            //Response.Redirect("login.aspx");
            Response.Write("<script>window.parent.location=\"login.aspx\";</script>");
            return;
        }
        else
        {
            hiddencompcode.Value = Session["compcode"].ToString();
            hiddenuserid.Value = Session["userid"].ToString();
            hiddendateformat.Value = Session["dateformat"].ToString();

        }*/

        // Put user code to initialize the page here
        Response.Expires = -1;
        hiddenusername.Value = Session["Username"].ToString();
        Ajax.Utility.RegisterTypeForAjax(typeof(RateGroupMaster));



        DataSet objDataSetbu = new DataSet();
        // Read in the XML file
        objDataSetbu.ReadXml(Server.MapPath("XML/button.xml"));
        btnNew.ImageUrl = objDataSetbu.Tables[0].Rows[0].ItemArray[0].ToString();
        btnSave.ImageUrl = objDataSetbu.Tables[0].Rows[0].ItemArray[1].ToString();
        btnModify.ImageUrl = objDataSetbu.Tables[0].Rows[0].ItemArray[2].ToString();
        btnQuery.ImageUrl = objDataSetbu.Tables[0].Rows[0].ItemArray[3].ToString();
        btnExecute.ImageUrl = objDataSetbu.Tables[0].Rows[0].ItemArray[4].ToString();
        btnCancel.ImageUrl = objDataSetbu.Tables[0].Rows[0].ItemArray[5].ToString();
        btnfirst.ImageUrl = objDataSetbu.Tables[0].Rows[0].ItemArray[6].ToString();
        btnprevious.ImageUrl = objDataSetbu.Tables[0].Rows[0].ItemArray[7].ToString();
        btnnext.ImageUrl = objDataSetbu.Tables[0].Rows[0].ItemArray[8].ToString();
        btnlast.ImageUrl = objDataSetbu.Tables[0].Rows[0].ItemArray[9].ToString();
        btnDelete.ImageUrl = objDataSetbu.Tables[0].Rows[0].ItemArray[10].ToString();
        btnExit.ImageUrl = objDataSetbu.Tables[0].Rows[0].ItemArray[11].ToString();



        DataSet ds = new DataSet();
        // Read in the XML file
        ds.ReadXml(Server.MapPath("XML/RateGroupMaster.xml"));

        RateGroupCode.Text = ds.Tables[0].Rows[0].ItemArray[0].ToString();
        RateGroupName.Text = ds.Tables[0].Rows[0].ItemArray[1].ToString();
        Alias.Text = ds.Tables[0].Rows[0].ItemArray[2].ToString();



        //Ajax.Utility.RegisterTypeForAjax(typeof(ClientMaster));
        navigation();

        btnNew.Focus();

        if (!Page.IsPostBack)
        {


            btnNew.Attributes.Add("OnClick", "javascript:return NewClick3();");
            btnSave.Attributes.Add("OnClick", "javascript:return SaveClick3();");
            btnModify.Attributes.Add("OnClick", "javascript:return ModifyClick3();");
            btnDelete.Attributes.Add("OnClick", "javascript:return DeleteClick3();");
            btnQuery.Attributes.Add("OnClick", "javascript:return QueryClick3();");
            btnExecute.Attributes.Add("OnClick", "javascript:return ExecuteClick3();");
            btnCancel.Attributes.Add("OnClick", "javascript:return CancelClick3('RateGroupMaster');");
            btnfirst.Attributes.Add("OnClick", "javascript:return FirstClick3();");
            btnprevious.Attributes.Add("OnClick", "javascript:return PreviousClick3();");
            btnnext.Attributes.Add("OnClick", "javascript:return NextClick3();");
            btnlast.Attributes.Add("OnClick", "javascript:return LastClick3();");
            btnExit.Attributes.Add("OnClick", "javascript:return ExitClick3();");


            txtAlias.Attributes.Add("OnChange", "javascript:return uppercase('txtAlias');");
            txtRtGroupCode.Attributes.Add("OnChange", "javascript:return uppercase('txtRtGroupCode');");
            txtRtGroupName.Attributes.Add("OnChange", "javascript:return uppercase('txtRtGroupName');");
            txtRtGroupName.Attributes.Add("OnChange", "javascript:return autoornot();");

        }
        if (btnNew.Enabled == false)
            btnNew.ImageUrl = objDataSetbu.Tables[1].Rows[0].ItemArray[0].ToString();
        if (btnSave.Enabled == false)
            btnSave.ImageUrl = objDataSetbu.Tables[1].Rows[0].ItemArray[1].ToString();
        if (btnModify.Enabled == false)
            btnModify.ImageUrl = objDataSetbu.Tables[1].Rows[0].ItemArray[2].ToString();
        if (btnQuery.Enabled == false)
            btnQuery.ImageUrl = objDataSetbu.Tables[1].Rows[0].ItemArray[3].ToString();
        if (btnExecute.Enabled == false)
            btnExecute.ImageUrl = objDataSetbu.Tables[1].Rows[0].ItemArray[4].ToString();
        if (btnCancel.Enabled == false)
            btnCancel.ImageUrl = objDataSetbu.Tables[1].Rows[0].ItemArray[5].ToString();
        if (btnfirst.Enabled == false)
            btnfirst.ImageUrl = objDataSetbu.Tables[1].Rows[0].ItemArray[6].ToString();
        if (btnprevious.Enabled == false)
            btnprevious.ImageUrl = objDataSetbu.Tables[1].Rows[0].ItemArray[7].ToString();
        if (btnnext.Enabled == false)
            btnnext.ImageUrl = objDataSetbu.Tables[1].Rows[0].ItemArray[8].ToString();
        if (btnlast.Enabled == false)
            btnlast.ImageUrl = objDataSetbu.Tables[1].Rows[0].ItemArray[9].ToString();
        if (btnDelete.Enabled == false)
            btnDelete.ImageUrl = objDataSetbu.Tables[1].Rows[0].ItemArray[10].ToString();
        if (btnExit.Enabled == false)
            btnExit.ImageUrl = objDataSetbu.Tables[1].Rows[0].ItemArray[11].ToString();
        // Put user code to initialize the page here
    }
    [Ajax.AjaxMethod]
    //		public DataSet modify(string RtGroupCode,string RtGroupName,string Alias,string compcode,string userid)
     public DataSet modify(string RtGroupCode, string RtGroupName, string Alias, string compcode, string userid)
    {
        DataSet ds = new DataSet();
        if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "sql")
        {
            NewAdbooking.Classes.RateGroupMaster modify = new NewAdbooking.Classes.RateGroupMaster();

            ds = modify.ModifyValue(RtGroupCode, RtGroupName, Alias, compcode, userid);
        }
        else if (ConfigurationSettings.AppSettings["Connectiontype"].ToString() == "orcl")
        {
            NewAdbooking.classesoracle.RateGroupMaster modify = new NewAdbooking.classesoracle.RateGroupMaster();
            ds = modify.ModifyValue(RtGroupCode, RtGroupName, Alias, compcode, userid);
        }
        else
        {
            NewAdbooking.classmysql.RateGroupMaster modify = new NewAdbooking.classmysql.RateGroupMaster();

            ds = modify.ModifyValue(RtGroupCode, RtGroupName, Alias, compcode, userid);
        }
        return ds;


    }


    [Ajax.AjaxMethod]
    //		public DataSet insert(string RtGroupCode,string RtGroupName,string Alias,string compcode,string userid)
     public DataSet insert(string RtGroupCode, string RtGroupName, string Alias, string compcode, string userid)
    {
        DataSet ds = new DataSet();
        if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "sql")
        {
            NewAdbooking.Classes.RateGroupMaster insert = new NewAdbooking.Classes.RateGroupMaster();

            ds = insert.InsertValue(RtGroupCode, RtGroupName, Alias, compcode, userid);
        }
        else if (ConfigurationSettings.AppSettings["Connectiontype"].ToString() == "orcl")
        {
            NewAdbooking.classesoracle.RateGroupMaster insert = new NewAdbooking.classesoracle.RateGroupMaster();

            ds = insert.InsertValue(RtGroupCode, RtGroupName, Alias, compcode, userid);
        }
        else
        {
            NewAdbooking.classmysql.RateGroupMaster insert = new NewAdbooking.classmysql.RateGroupMaster();

            ds = insert.InsertValue(RtGroupCode, RtGroupName, Alias, compcode, userid);
        }
        return ds;
    }

    [Ajax.AjaxMethod]
    //		public DataSet Select(string RtGroupCode,string RtGroupName,string Alias,string compcode,string userid)
     public DataSet Select(string RtGroupCode, string RtGroupName, string Alias, string compcode, string userid)
    {
        DataSet ds = new DataSet();
        if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "sql")
        {
            NewAdbooking.Classes.RateGroupMaster select = new NewAdbooking.Classes.RateGroupMaster();

            ds = select.SelectValue(RtGroupCode, RtGroupName, Alias, compcode, userid);
        }

        else if (ConfigurationSettings.AppSettings["Connectiontype"].ToString() == "orcl")
        {
            NewAdbooking.classesoracle.RateGroupMaster select = new NewAdbooking.classesoracle.RateGroupMaster();
            ds = select.SelectValue(RtGroupCode, RtGroupName, Alias, compcode, userid);
        }
        else
        {
            NewAdbooking.classmysql.RateGroupMaster select = new NewAdbooking.classmysql.RateGroupMaster();
            ds = select.SelectValue(RtGroupCode, RtGroupName, Alias, compcode, userid);
        }
        return ds;
    }

    [Ajax.AjaxMethod]
    //		public DataSet Selectfnpl(string RtGroupCode,string RtGroupName,string Alias,string compcode,string userid)
     public DataSet Selectfnpl(string RtGroupCode, string RtGroupName, string Alias, string compcode, string userid)
    {
        DataSet ds = new DataSet();
        if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "sql")
        {
            NewAdbooking.Classes.RateGroupMaster select = new NewAdbooking.Classes.RateGroupMaster();
            ds = select.Selectfnpl(RtGroupCode, RtGroupName, Alias, compcode, userid);
            //ds=agentmastersave.saveagent(comp,drpagetype,drpagecate,drpagescat,txtagencode,txtagenname,txtalias,txtagenho,txtadd,txtstreet,drpcity,txtzip,txtdistrict,txtstate,txtcountry,txtphone2,txtmail,txtfax,txturl,txtbussinessdate,txtenrolldate,txtmyrefno,txtnoofvts,txtcredit,txtpan,txttan,txtsagencycod,paymode,txtstatus2,txtremarks,userid,txtsubagenho,txtsagencycode,txtbill,txtalert,txtcrlimit,txtphone1,drpress,txtpincode,drpregion);
        }
        else if (ConfigurationSettings.AppSettings["Connectiontype"].ToString() == "orcl")
        {
            NewAdbooking.classesoracle.RateGroupMaster select = new NewAdbooking.classesoracle.RateGroupMaster();
            ds = select.SelectValue(RtGroupCode, RtGroupName, Alias, compcode, userid);
        }

        else
        {
            NewAdbooking.classmysql.RateGroupMaster select = new NewAdbooking.classmysql.RateGroupMaster();
            ds = select.Selectfnpl(RtGroupCode, RtGroupName, Alias, compcode, userid);
            //ds=agentmastersave.saveagent(comp,drpagetype,drpagecate,drpagescat,txtagencode,txtagenname,txtalias,txtagenho,txtadd,txtstreet,drpcity,txtzip,txtdistrict,txtstate,txtcountry,txtphone2,txtmail,txtfax,txturl,txtbussinessdate,txtenrolldate,txtmyrefno,txtnoofvts,txtcredit,txtpan,txttan,txtsagencycod,paymode,txtstatus2,txtremarks,userid,txtsubagenho,txtsagencycode,txtbill,txtalert,txtcrlimit,txtphone1,drpress,txtpincode,drpregion);
        }

        return ds;


    }
    [Ajax.AjaxMethod]
    //		public DataSet deleteRate(string RtGroupCode,string compcode,string userid)	 	
     public DataSet deleteRate(string RtGroupCode, string compcode, string userid)
    {
        DataSet ds = new DataSet();
        if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "sql")
        {
            NewAdbooking.Classes.RateGroupMaster delete = new NewAdbooking.Classes.RateGroupMaster();
            ds = delete.DeleteValue(RtGroupCode, compcode, userid);
            //ds=agentmastersave.saveagent(comp,drpagetype,drpagecate,drpagescat,txtagencode,txtagenname,txtalias,txtagenho,txtadd,txtstreet,drpcity,txtzip,txtdistrict,txtstate,txtcountry,txtphone2,txtmail,txtfax,txturl,txtbussinessdate,txtenrolldate,txtmyrefno,txtnoofvts,txtcredit,txtpan,txttan,txtsagencycod,paymode,txtstatus2,txtremarks,userid,txtsubagenho,txtsagencycode,txtbill,txtalert,txtcrlimit,txtphone1,drpress,txtpincode,drpregion);
        }
        else if (ConfigurationSettings.AppSettings["Connectiontype"].ToString() == "orcl")
        {
            NewAdbooking.classesoracle.RateGroupMaster delete = new NewAdbooking.classesoracle.RateGroupMaster();
            ds = delete.DeleteValue(RtGroupCode, compcode, userid);
        }
        else
        {
            NewAdbooking.classmysql.RateGroupMaster delete = new NewAdbooking.classmysql.RateGroupMaster();
            ds = delete.DeleteValue(RtGroupCode, compcode, userid);
            //ds=agentmastersave.saveagent(comp,drpagetype,drpagecate,drpagescat,txtagencode,txtagenname,txtalias,txtagenho,txtadd,txtstreet,drpcity,txtzip,txtdistrict,txtstate,txtcountry,txtphone2,txtmail,txtfax,txturl,txtbussinessdate,txtenrolldate,txtmyrefno,txtnoofvts,txtcredit,txtpan,txttan,txtsagencycod,paymode,txtstatus2,txtremarks,userid,txtsubagenho,txtsagencycode,txtbill,txtalert,txtcrlimit,txtphone1,drpress,txtpincode,drpregion);
        }

        return ds;


    }

    [Ajax.AjaxMethod]
    //		public DataSet chkrategroup(string RtGroupCode,string compcode,string userid)
     public DataSet chkrategroup(string RtGroupCode, string RtGroupName,string compcode, string userid)
    {
        DataSet ds = new DataSet();
        if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "sql")
        {
            NewAdbooking.Classes.RateGroupMaster chkcode = new NewAdbooking.Classes.RateGroupMaster();
            ds = chkcode.chkvalue(RtGroupCode,RtGroupName, compcode, userid);
        }
        else if (ConfigurationSettings.AppSettings["Connectiontype"].ToString() == "orcl")
        {
            NewAdbooking.classesoracle.RateGroupMaster chkcode = new NewAdbooking.classesoracle.RateGroupMaster();
            ds = chkcode.chkvalue(RtGroupCode,RtGroupName, compcode, userid);
        }
        else
        {
            NewAdbooking.classmysql.RateGroupMaster chkcode = new NewAdbooking.classmysql.RateGroupMaster();
            ds = chkcode.chkvalue(RtGroupCode, RtGroupName, compcode, userid);
        }
        return ds;
    }

    [Ajax.AjaxMethod]
    public DataSet chkrgroupcode(string str)
    {
        DataSet ds = new DataSet();
        if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "sql")
        {
            NewAdbooking.Classes.RateGroupMaster chk = new NewAdbooking.Classes.RateGroupMaster();
            ds = chk.chkrgroupcode1(str);
        }
        else if (ConfigurationSettings.AppSettings["Connectiontype"].ToString() == "orcl")
        {
            NewAdbooking.classesoracle.RateGroupMaster chk = new NewAdbooking.classesoracle.RateGroupMaster();
            ds = chk.chkrgroupcode1(str);
        }
        else
        {
            NewAdbooking.classmysql.RateGroupMaster chk = new NewAdbooking.classmysql.RateGroupMaster();
            ds = chk.chkrgroupcode1(str);
        }
        return ds;

    }





    //		public void navigation()
     public void navigation()
    {

        btnNew.Enabled = true;
        btnSave.Enabled = false;
        btnModify.Enabled = false;
        btnDelete.Enabled = false;
        btnQuery.Enabled = true;
        btnExecute.Enabled = false;
        btnCancel.Enabled = true;
        btnfirst.Enabled = false;
        btnprevious.Enabled = false;
        btnnext.Enabled = false;
        btnlast.Enabled = false;
        btnExit.Enabled = true;
        //btncomname.Enabled=false;

    }
    #region Web Form Designer generated code
     protected void OnInit(EventArgs e)
    {
        //
        // CODEGEN: This call is required by the ASP.NET Web Form Designer.
        //
        InitializeComponent();
        base.OnInit(e);
    }

    /// <summary>
    /// Required method for Designer support - do not modify
    /// the contents of this method with the code editor.
    /// </summary>
    private void InitializeComponent()
    {

    }
    #endregion
}