using System;
using System.Data;
using System.Configuration;
using System.Collections;
using System.Web;
using System.Web.Security;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.HtmlControls;
using System.Data.SqlClient;
using System.Web.Mail;
public partial class unconfirmad : System.Web.UI.Page
{

    int i = 0;
    int j = 0;
    protected void Page_Load(object sender, EventArgs e)
    {
        Response.Expires = -1;
        DataGrid1.Visible = true;
        //drprevenu.Text = "VIBHA AGENCY(VI0VIB0)";
    //    Session["compcode"] = "HT001";
       
        if (Session["compcode"] == null)
        {
            Response.Redirect("login.aspx");
            Response.Write("<script>window.parent.location=\"login.aspx\";</script>");
            return;
        }
        hiddencomcode.Value = Session["compcode"].ToString();
        hiddencompcode.Value = Session["compcode"].ToString();
        hiddenuserid.Value = Session["userid"].ToString();
        hiddendateformat.Value = Session["dateformat"].ToString();
        hiddenusername.Value = Session["Username"].ToString();
        hiddenauto.Value = Session["autogenerated"].ToString();

        DataSet ds1 = new DataSet();
        if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "sql")
        {
            NewAdbooking.Classes.unconfirmpaidad executebullet = new NewAdbooking.Classes.unconfirmpaidad();
            ds1 = executebullet.bindsh(Session["userid"].ToString(), Session["compcode"].ToString());
        }
        else
        {
            NewAdbooking.classesoracle.unconfirmpaidad executebullet = new NewAdbooking.classesoracle.unconfirmpaidad();
            ds1 = executebullet.bindsh(Session["userid"].ToString(), Session["compcode"].ToString());

        }
        if (ds1.Tables[0].Rows.Count>0)
        hiddensh.Value = ds1.Tables[0].Rows[0].ItemArray[0].ToString();
        Ajax.Utility.RegisterTypeForAjax(typeof(unconfirmad));
        if (!Page.IsPostBack)
        {
            if (Session["agency_name"] != null && Session["agency_name"].ToString() != "0" && Session["agency_name"].ToString() != "")
            {
                drprevenu.Enabled = false;
                DataSet ds11 = new DataSet();
                if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "sql")
                {
                    NewAdbooking.Classes.Master ms1 = new NewAdbooking.Classes.Master();
                    ds11 = ms1.GetAgencyNameAdd_agency(Session["agency_name"].ToString(), Session["compcode"].ToString(), "0");
                }
                else
                {
                    NewAdbooking.classesoracle.Master ms1 = new NewAdbooking.classesoracle.Master();
                    ds11 = ms1.GetAgencyNameAdd_agency(Session["agency_name"].ToString(), Session["compcode"].ToString(), "0");

                }
                if (ds11.Tables[0].Rows.Count > 0)
                {
                    drprevenu.Text = ds11.Tables[0].Rows[0].ItemArray[1].ToString() + "(" + Session["agency_name"].ToString() + ")";
                }
            }

            bindadvtype();
            fillPubCenter(Session["compcode"].ToString());
            //bindagencydrp();
            form1.Attributes.Add("onload", "javascript:return display();");
            btnsubmit.Attributes.Add("OnClick", "javascript:return executeclick();");
            btnrefresh.Attributes.Add("OnClick", "javascript:return refresh();");
            btnmodify.Attributes.Add("OnClick", "javascript:openbookingModify();");
            btnpreview.Attributes.Add("OnClick", "javascript:return openPrev();");
            //drprevenu.Attributes.Add("OnChange", "javascript:return bindQBC();");
            btnclear.Attributes.Add("OnClick", "javascript:return cleardata();");
            btnbookingaudit.Attributes.Add("OnClick", "javascript:return bookingaudit2();");
            btnsave1.Attributes.Add("OnClick", "javascript:return save1();");
            lstagency.Attributes.Add("onclick", "javascript:return insertagency();");
            //adtypedata(Session["compcode"].ToString());
            //fillPubCenter(Session["compcode"].ToString());
            btnaudit.Enabled = false;
            btnpreview.Enabled = false;
            btnunaudit.Enabled = false;
            btnsave1.Enabled = false;
        }
        //bindagencydrp();


        //********************************For Label****************************************/
        DataSet ds = new DataSet();
        ds.ReadXml(Server.MapPath("XML/unconfirmpaidad.xml"));
        lblvfrm.Text = ds.Tables[0].Rows[0].ItemArray[0].ToString();
        lblvalidtill.Text = ds.Tables[0].Rows[0].ItemArray[1].ToString();
        
        lblagency.Text = ds.Tables[0].Rows[0].ItemArray[2].ToString();
        lbluom.Text = ds.Tables[0].Rows[0].ItemArray[3].ToString();
        lblagreedrate.Text = ds.Tables[0].Rows[0].ItemArray[4].ToString();
        lblclient.Text = ds.Tables[0].Rows[0].ItemArray[5].ToString();
        
        lblpackage.Text = ds.Tables[0].Rows[0].ItemArray[6].ToString();
        
        lblagreedamount.Text = ds.Tables[0].Rows[0].ItemArray[7].ToString();
        
        lblpaymode.Text = ds.Tables[0].Rows[0].ItemArray[8].ToString();
        lblpublichdate.Text = ds.Tables[0].Rows[0].ItemArray[9].ToString();
       
        lbldiscount.Text = ds.Tables[0].Rows[0].ItemArray[10].ToString();
        lblrono.Text = ds.Tables[0].Rows[0].ItemArray[11].ToString();
        lblnoofinsertion.Text = ds.Tables[0].Rows[0].ItemArray[12].ToString();
        lblpositionpremium.Text = ds.Tables[0].Rows[0].ItemArray[13].ToString();
        lblrostatus.Text = ds.Tables[0].Rows[0].ItemArray[14].ToString();
        
        lblpaid.Text = ds.Tables[0].Rows[0].ItemArray[15].ToString();
        lblspecialdiscount.Text = ds.Tables[0].Rows[0].ItemArray[16].ToString();
        
        lblexecutivename.Text = ds.Tables[0].Rows[0].ItemArray[17].ToString();
        lblcontractname.Text = ds.Tables[0].Rows[0].ItemArray[18].ToString();
        lblspacediscount.Text = ds.Tables[0].Rows[0].ItemArray[19].ToString();
        lbloutstanding.Text = ds.Tables[0].Rows[0].ItemArray[20].ToString();
        //lblbrand.Text = ds.Tables[0].Rows[0].ItemArray[21].ToString();
        lblheight.Text = ds.Tables[0].Rows[0].ItemArray[21].ToString();
        //lblproduct.Text = ds.Tables[0].Rows[0].ItemArray[22].ToString();
        lblspecialcharge.Text = ds.Tables[0].Rows[0].ItemArray[22].ToString();
        lblretainername.Text = ds.Tables[0].Rows[0].ItemArray[23].ToString();
        lbllines.Text = ds.Tables[0].Rows[0].ItemArray[24].ToString();
        lbladdagecomm.Text = ds.Tables[0].Rows[0].ItemArray[25].ToString();
        //lblnocolumns.Text = ds.Tables[0].Rows[0].ItemArray[26].ToString();
        lblbookingtype.Text = ds.Tables[0].Rows[0].ItemArray[26].ToString();
        lblpageposition.Text = ds.Tables[0].Rows[0].ItemArray[27].ToString();
        lblgrossamt.Text = ds.Tables[0].Rows[0].ItemArray[28].ToString();
        //lblcurrency.Text = ds.Tables[0].Rows[0].ItemArray[29].ToString();
        lblcolourtype.Text = ds.Tables[0].Rows[0].ItemArray[29].ToString();
        lblpositionpre.Text = ds.Tables[0].Rows[0].ItemArray[30].ToString();
        lblretainercommission.Text = ds.Tables[0].Rows[0].ItemArray[31].ToString();
        lbladcategory.Text = ds.Tables[0].Rows[0].ItemArray[32].ToString();
        lblarea.Text = ds.Tables[0].Rows[0].ItemArray[33].ToString();
        lblagtradediscount.Text = ds.Tables[0].Rows[0].ItemArray[34].ToString();
        lbladsubcat1.Text = ds.Tables[0].Rows[0].ItemArray[35].ToString();
        lblschemetype.Text = ds.Tables[0].Rows[0].ItemArray[36].ToString();
        lblbillamount.Text = ds.Tables[0].Rows[0].ItemArray[37].ToString();
        lbladsubcat2.Text = ds.Tables[0].Rows[0].ItemArray[38].ToString();
        lblratecode.Text = ds.Tables[0].Rows[0].ItemArray[39].ToString();
        lbladsubcat3.Text = ds.Tables[0].Rows[0].ItemArray[40].ToString();
        lblcardrate.Text = ds.Tables[0].Rows[0].ItemArray[41].ToString();
        lbladsubcat4.Text = ds.Tables[0].Rows[0].ItemArray[42].ToString();
        lblcardamount.Text = ds.Tables[0].Rows[0].ItemArray[43].ToString();
        lblremarks.Text = ds.Tables[0].Rows[0].ItemArray[44].ToString();
        Label2.Text = ds.Tables[0].Rows[0].ItemArray[45].ToString();
        /////////////////add by anuja
        lblprint.Text = ds.Tables[0].Rows[0].ItemArray[46].ToString();
        ////////////////////////////////////////////////////////
        txtagency.Enabled = false;
       
        txtratecode.Enabled = false;
        txtclient.Enabled = false;
        
        txtadsubcat4.Enabled = false;
        txtcardrate.Enabled = false;
        txtagtradediscount.Enabled = false;
        txtagreedamount.Enabled = false;
        txtarea.Enabled = false;
        txtagreedrate.Enabled = false;
        txtgrossamt.Enabled = false;
        txtcardamount.Enabled = false;
        txtcontractname.Enabled = false;
        txtaddagecomm.Enabled = false;
        txtpackage.Enabled = false;
        txtdiscount.Enabled = false;
        txtpageposition.Enabled = false;
        txtexecutivename.Enabled = false;
        txtlines.Enabled = false;
        txtbookingtype.Enabled = false;
        txtheight.Enabled = false;
        txtcolourtype.Enabled = false;
       
        txtwidth.Enabled = false;
        txtspecialdiscount.Enabled = false;
        txtdiscount.Enabled = false;
        txtagreedrate.Enabled = false;
        txtschemetype.Enabled = false;
        txtpositionpre.Enabled = false;
        txtpaid.Enabled = false;
        txtpublishdate.Enabled = false;
        txtpositionpremium.Enabled = false;
        txtretainercommission.Enabled = false;
        txtadcategory.Enabled = false;
        txtadsubcat1.Enabled = false;
        txtuom.Enabled = false;
        txtoutstanding.Enabled = false;
        txtadsubcat2.Enabled = false;
        txtspecialcharge.Enabled = false;
        txtadsubcat3.Enabled = false;
        txtrono.Enabled = false;
        txtrostatus.Enabled = false;
        txtretainername.Enabled = false;
        txtpaymode.Enabled = false;
        txtnoofinsertion.Enabled = false;
        txtspacediscount.Enabled = false;
        txtbillamount.Enabled = false;
        txtremarks.Enabled = false;
        btnmodify.Enabled = false;

    }
    protected void btnsubmit_Click(object sender, EventArgs e)
    {
        DataSet ds = new DataSet();
        string revcenter = "";
        if (drprevenu.Text != "")
        {
            revcenter = drprevenu.Text.Substring(drprevenu.Text.LastIndexOf("(") + 1, drprevenu.Text.Length - drprevenu.Text.LastIndexOf("(") - 2);
        }
        if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "sql")
        {
            NewAdbooking.Classes.unconfirmpaidad abc = new NewAdbooking.Classes.unconfirmpaidad();
            ds = abc.bindgrid(Session["dateformat"].ToString(), txttilldate.Text, txtvalidityfrom.Text, revcenter, "0", drpconfirm.SelectedValue, drprinting.SelectedValue, drpadtype.SelectedValue);
        }
        else
        {
            NewAdbooking.classesoracle.unconfirmpaidad abc = new NewAdbooking.classesoracle.unconfirmpaidad();
            ds = abc.bindgrid(Session["dateformat"].ToString(), txttilldate.Text, txtvalidityfrom.Text, revcenter, "0", drpconfirm.SelectedValue, Session["center"].ToString(), drpadtype.SelectedValue);
        }
        if (ds.Tables[0].Rows.Count <= 0)
        {
            string sessionout = "Confirm Ads to be paid in Cash at HTML are not found";
            AspNetMessageBox_close(sessionout);
        }
        else
        {
            Session["RowLen"] = ds.Tables[0].Rows.Count;
            DataGrid1.DataSource = ds;
            DataGrid1.DataBind();
        }



    }
    protected void AspNetMessageBox_close(string strMessage)
    {
        //strMessage = adminResource.GetStringFromResource(strMessage); 
        string strAlert = "";
        strAlert = "document.getElementById('divgrid1').style.display='none';alert('" + strMessage + "');";
        ScriptManager.RegisterClientScriptBlock(this, typeof(unconfirmad), "ShowAlert", strAlert, true);
    }
    [Ajax.AjaxMethod(Ajax.HttpSessionStateRequirement.Read)]
    public DataSet execute(string bookingid, string compcode, string adtype)
    {
        DataSet ds = new DataSet();
        if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "sql")
        {
            NewAdbooking.Classes.unconfirmpaidad executebullet = new NewAdbooking.Classes.unconfirmpaidad();
            ds = executebullet.executeauditmast1(bookingid, compcode, adtype, Session["dateformat"].ToString());
        }
        else
        {
            NewAdbooking.classesoracle.unconfirmpaidad executebullet = new NewAdbooking.classesoracle.unconfirmpaidad();
            ds = executebullet.executeauditmast1(bookingid, compcode, adtype, Session["dateformat"].ToString(),Session["userid"].ToString());
           
        }


        return ds;
    }
   
    protected void btnclear_Click(object sender, EventArgs e)
    {
        
    }
    protected void DataGrid1_ItemDataBound(object sender, DataGridItemEventArgs e)
    {
        if (hiddensh.Value == "Y")
        {
            hiddenrowcount.Value = Session["RowLen"].ToString();
            if (e.Item.ItemType == ListItemType.Header)
            {
                if (drpconfirm.SelectedValue == "1")
                {
                    e.Item.Cells[0].Text = "<input type='checkbox' disabled id='checkall' onclick=\"javascript:return selectAll();\" />";
                }
                else
                {
                    e.Item.Cells[0].Text = "<input type='checkbox' id='checkall' onclick=\"javascript:return selectAll();\" />";
                }
            }
            if (e.Item.ItemType == ListItemType.Item || e.Item.ItemType == ListItemType.AlternatingItem)
            {
                string str = "chk" + j;
                if (e.Item.Cells[4].Text != "&nbsp;" || drpconfirm.SelectedValue == "1")
                    e.Item.Cells[0].Text = "<input type='checkbox' id=" + str + " disabled   value='" + e.Item.Cells[2].Text + "'  />";
                else
                    e.Item.Cells[0].Text = "<input type='checkbox' id=" + str + "   value='" + e.Item.Cells[2].Text + "'  />";


                //if (e.Item.Cells[4].Text != "&nbsp;")
                //{
                //    e.Item.Cells[1].Text = "<img src=\"images/flag.gif\" ></img>";
                //}
                string bookingid = e.Item.Cells[2].Text;
                e.Item.Cells[2].Text = "<a id='cio" + i + "' style=\"cursor:hand;color:blue\" onClick=\"openbooking('" + e.Item.Cells[2].Text + "','cio" + i + "','" + hiddenrowcount.Value + "','" + e.Item.Cells[5].Text + "','')\">" + e.Item.Cells[2].Text + "</a>";
                i = i + 1;
                j++;
            }
        }
        else
        {
            hiddenrowcount.Value = Session["RowLen"].ToString();
            if (e.Item.ItemType == ListItemType.Header)
            {
                if (drpconfirm.SelectedValue == "1")
                {
                    e.Item.Cells[0].Text = "<input type='checkbox' disabled id='checkall' onclick=\"javascript:return selectAll();\" />";
                }
                else
                {
                    e.Item.Cells[0].Text = "<input type='checkbox'  id='checkall' onclick=\"javascript:return selectAll();\" />";
                }
            }
            if (e.Item.ItemType == ListItemType.Item || e.Item.ItemType == ListItemType.AlternatingItem)
            {
                string str = "chk" + j;
                if (drpconfirm.SelectedValue == "1")
                    e.Item.Cells[0].Text = "<input type='checkbox' id=" + str + " disabled   value='" + e.Item.Cells[2].Text + "'  />";
                else
                    e.Item.Cells[0].Text = "<input type='checkbox' id=" + str + "    value='" + e.Item.Cells[2].Text + "'  />";


                //if (e.Item.Cells[4].Text != "&nbsp;")
                //{
                //    e.Item.Cells[1].Text = "<img src=\"images/flag.gif\" ></img>";
                //}
                string bookingid = e.Item.Cells[2].Text;
                e.Item.Cells[2].Text = "<a id='cio" + i + "' style=\"cursor:hand;color:blue\" onClick=\"openbooking('" + e.Item.Cells[2].Text + "','cio" + i + "','" + hiddenrowcount.Value + "','" + e.Item.Cells[5].Text + "','')\">" + e.Item.Cells[2].Text + "</a>";
                i = i + 1;
                j++;
            }
        }
    }




    public void bindadvtype()
    {
        //regionhidden=hiddenregion.Value;
        DataSet ds = new DataSet();
        if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "sql")
        {
            NewAdbooking.Classes.AdCategoryMaster advname = new NewAdbooking.Classes.AdCategoryMaster();

            ds = advname.adname(Session["compcode"].ToString());
        }
        else if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "orcl")
        {
            NewAdbooking.classesoracle.AdCategoryMaster advname = new NewAdbooking.classesoracle.AdCategoryMaster();
            ds = advname.adname(Session["compcode"].ToString());
        }
        else
        {
            NewAdbooking.classmysql.AdCategoryMaster advname = new NewAdbooking.classmysql.AdCategoryMaster();
            ds = advname.adname(Session["compcode"].ToString());
        }
        ListItem li1;
        li1 = new ListItem();
        li1.Text = "--Select Ad Type--";
        li1.Value = "0";//objDataSet.Tables[0].Rows[i].ItemArray[0].ToString();
        li1.Selected = true;
        drpadtype.Items.Add(li1);

        int i;
        for (i = 0; i < ds.Tables[0].Rows.Count; i++)
        {
            ListItem li;
            li = new ListItem();
            li.Value = ds.Tables[0].Rows[i].ItemArray[0].ToString();
            li.Text = ds.Tables[0].Rows[i].ItemArray[1].ToString();
            drpadtype.Items.Add(li);


        }
    }

    protected void DataGrid1_SelectedIndexChanged(object sender, EventArgs e)
    {

    }

    [Ajax.AjaxMethod(Ajax.HttpSessionStateRequirement.Read)]

    public void updateStatus2(string booking_id)
    {
        DataSet ds = new DataSet();
        if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "sql")
        {
            NewAdbooking.Classes.unconfirmpaidad up = new NewAdbooking.Classes.unconfirmpaidad();
            ds = up.update1(booking_id, Session["userid"].ToString());
        }
        else
            if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "orcl")
            {
                NewAdbooking.classesoracle.unconfirmpaidad up = new NewAdbooking.classesoracle.unconfirmpaidad();
                ds = up.update1(booking_id,Session["userid"].ToString());
            }
            else
            {
                //NewAdbooking.classmysql.Booking_Audit1 up = new NewAdbooking.classmysql.Booking_Audit1();
                //ds = up.update1(booking_id,auditname);
            }

    }
    [Ajax.AjaxMethod]
    public void AUTOtag(string cioid, string agency)
    {
        if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "sql")
        {
            NewAdbooking.Classes.unconfirmpaidad up = new NewAdbooking.Classes.unconfirmpaidad();
            
            up.AUTOtag(cioid, agency);
        }
    }
    [Ajax.AjaxMethod(Ajax.HttpSessionStateRequirement.Read)]
    public void updateStatus3(string booking_id)
    {
        DataSet ds = new DataSet();
        if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "sql")
        {
            NewAdbooking.Classes.unconfirmpaidad up = new NewAdbooking.Classes.unconfirmpaidad();
            ds = up.update2(booking_id);
        }
        else
            if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "orcl")
            {
                NewAdbooking.classesoracle.unconfirmpaidad up = new NewAdbooking.classesoracle.unconfirmpaidad();
                ds = up.update2(booking_id);
            }
            else
            {
                //NewAdbooking.classmysql.Booking_Audit1 up = new NewAdbooking.classmysql.Booking_Audit1();
                //ds = up.update1(booking_id,auditname);
            }
      //  string mail_id="";
      //  if (ds.Tables[0].Rows[0]["execmailid"].ToString() != "" && ds.Tables[0].Rows[0]["execmailid"].ToString() != "NULL" && ds.Tables[0].Rows[0]["execmailid"].ToString() != null)
      //      mail_id = ds.Tables[0].Rows[0]["execmailid"].ToString();
      //  else if (ds.Tables[0].Rows[0]["reianeremailid"].ToString() != "" && ds.Tables[0].Rows[0]["reianeremailid"].ToString() != "NULL" && ds.Tables[0].Rows[0]["reianeremailid"].ToString() != null)
      //      mail_id = ds.Tables[0].Rows[0]["reianeremailid"].ToString();
      //  else
      //  {
      //      mail_id = "parasana@gmail.com";
      //  }

      //  System.Web.Mail.MailMessage msgMail = new System.Web.Mail.MailMessage();
      //  msgMail.From="head.scheduling@manipalmedia.com";
      //  msgMail.To = mail_id;

      //  msgMail.Subject = "Booking without R.O";
        
      //  string str = "";
      //  //string strBody = "Booking Id " + booking_id + " with Dockit No. " + ds.Tables[0].Rows[0]["dockit_no"].ToString() + " has been confirmed by User "+ Session["username"].ToString();
      //  str = str = "<table cellpadding='0' cellspacing='0' width=95% border='0' >";
      //  str += "<tr><td>Dear Sir / Madam,</td></tr>";
      //  str += "<tr></tr>";
      //  str += "<tr></tr>";
      //  str += "<tr><td>This is for your information, that this booking " + booking_id + " is not carrying with any R.O details. We are confirming this AD & we require the original R.O immediately.</td></tr>";
      //  str += "<tr></tr>";
      //  str += "<tr></tr>";
      //  str += "<tr><td>Kindly confirm the same.</td></tr>";
      //  str += "<tr></tr>";
      //  str += "<tr></tr>";
      //  str += "<tr><td>Thanks & Regards</td></tr>";
      //  str += "<tr></tr>";
      //  str += "<tr></tr>";
      //  str += "<tr><td>Scheduling Head</td></tr>";
      //  str += "<tr><td>Manipal Media Network Ltd.</td></tr>";
      //  str += "<tr><td>Manipal 576104</td></tr>";
      //  str += "</table>";
      //  string strBody = str;
      //  msgMail.BodyFormat = System.Web.Mail.MailFormat.Html;
      //  msgMail.Body = strBody;
      //  //System.Threading.Thread.Sleep(2000);

      //  msgMail.Cc = "malathi@manipalmedia.com,sathish@manipalmedia.com,parasana@gmail.com";
      // // msgMail.CC.Add("sathish@manipalmedia.com");
      // // msgMail.CC.Add("parasana@gmail.com");
      // // string PATH = Server.MapPath(".") + "\\PRINTPDF\\" + sFile;

      //  //System.Net.Mail.Attachment myAttachment = new System.Net.Mail.Attachment(PATH);

      // // msgMail.Attachments.Add(myAttachment);
      //  //System.Net.Mail.SmtpClient sc = new System.Net.Mail.SmtpClient();
      //  SmtpMail.SmtpServer = "192.168.5.38";
      // // sc.Host = "192.168.5.38";
      ////  sc.Send(msgMail);
      //  SmtpMail.Send(msgMail);
      //  Response.Write("Email was queued to disk");
    }
    protected void btnaudit_Click3(object sender, EventArgs e)
    {
        btnsubmit_Click(sender, e);
    }
    protected void btnmodify_Click(object sender, EventArgs e)
    {
        txtagency.Text = "";
        txtclient.Text = "";
        txtadsubcat2.Text = "";
        txtcardrate.Text = "";
        txtagreedamount.Text = "";
        txtretainername.Text = "";
        txtpaymode.Text = "";
        txtaddagecomm.Text = "";
        txtpageposition.Text = "";
        txtrono.Text = "";
        txtrostatus.Text = "";
        txtgrossamt.Text = "";
        txtspecialcharge.Text = "";
        txtexecutivename.Text = "";
        txtbookingtype.Text = "";
        txtoutstanding.Text = "";
        txtadcategory.Text = "";
        txtpositionpre.Text = "";
        txtarea.Text = "";
        txtretainercommission.Text = "";
        txtuom.Text = "";
        txtagtradediscount.Text = "";
        txtpositionpremium.Text = "";
        txtadsubcat1.Text = "";
        txtheight.Text = "";
        txtwidth.Text = "";
        txtpackage.Text = "";
        txtcolourtype.Text = "";
        txtnoofinsertion.Text = "";
        txtpublishdate.Text = "";
        txtcontractname.Text = "";
        txtschemetype.Text = "";
        txtpaid.Text = "";
        txtcardamount.Text = "";
        txtspecialdiscount.Text = "";
        txtdiscount.Text = "";
        txtagreedrate.Text = "";
        txtlines.Text = "";
        txtspacediscount.Text = "";
        txtadsubcat3.Text = "";
        txtadsubcat4.Text = "";
        txtratecode.Text = "";
        txtbillamount.Text = "";
        txtremarks.Text = "";

    }
    


    //public void bindagencydrp()
    //{
    //    DataSet ds;
    //    drprevenu.Items.Clear();
    //    if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "sql")
    //    {
    //        NewAdbooking.Classes.login logindetail = new NewAdbooking.Classes.login();
    //        ds = logindetail.getPubCenterAgency(Session["center"].ToString());
    //    }

    //    else
    //        if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "orcl")
    //        {
    //            NewAdbooking.classesoracle.login logindetail = new NewAdbooking.classesoracle.login();
    //            ds = logindetail.getPubCenterAgency(Session["center"].ToString());
    //        }
    //        else
    //        {
    //            NewAdbooking.classmysql.login logindetail = new NewAdbooking.classmysql.login();
    //            ds = logindetail.getPubCenter();
    //        }

    //    ListItem li1;
    //    li1 = new ListItem();
    //    li1.Text = "Select Agency";
    //    li1.Value = "0";
    //    li1.Selected = true;
    //    //drpagency.Items.Add(li1);
    //    drprevenu.Items.Add(li1);

    //    int i;
    //    for (i = 0; i < ds.Tables[0].Rows.Count; i++)
    //    {
    //        ListItem li;
    //        li = new ListItem();
    //        li.Text = ds.Tables[0].Rows[i].ItemArray[0].ToString();
    //        li.Value = ds.Tables[0].Rows[i].ItemArray[1].ToString();
    //        drprevenu.Items.Add(li);
    //    }
    //    if (Session["agency_name"] != null && Session["agency_name"].ToString() != "0" && Session["agency_name"].ToString() != "")
    //    {
    //        drprevenu.SelectedValue = Session["agency_name"].ToString();
    //        drprevenu.Enabled = false;
    //    }
    //}

    [Ajax.AjaxMethod(Ajax.HttpSessionStateRequirement.Read)]
    public DataSet bindagencyname(string compcode, string userid, string agency, string fla)
    {
        DataSet ds = new DataSet();
        if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "sql")
        {
            NewAdbooking.Classes.BookingMaster bindagenname = new NewAdbooking.Classes.BookingMaster();
            if (Session["FILTER"].ToString() == "D")
            {
                if (ConfigurationSettings.AppSettings["agencyf2"].ToString() == "Y" && fla == "Y")
                    ds = bindagenname.bind10agency(compcode, userid, agency, Session["revenue"].ToString());
                else
                    ds = bindagenname.bindagency(compcode, userid, agency, Session["revenue"].ToString());
            }

            else if (Session["FILTER"].ToString() == "P")
            {
                if (ConfigurationSettings.AppSettings["agencyf2"].ToString() == "Y" && fla == "Y")
                    ds = bindagenname.bind10agency(compcode, userid, agency, Session["center"].ToString());
                else
                    ds = bindagenname.bindagency(compcode, userid, agency, Session["center"].ToString());
            }
            else
            {
                if (ConfigurationSettings.AppSettings["agencyf2"].ToString() == "Y" && fla == "Y")
                    ds = bindagenname.bind10agency(compcode, userid, agency, "0");
                else
                    ds = bindagenname.bindagency(compcode, userid, agency, "0");
            }
        }
        else
            if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "orcl")
            {
                NewAdbooking.classesoracle.BookingMaster bindagenname = new NewAdbooking.classesoracle.BookingMaster();
                if (ConfigurationSettings.AppSettings["CLIENTNAME"].ToString() == "DJ")
                {
                    ds = bindagenname.bindagency_DJ(compcode, userid, agency, Session["revenue"].ToString(), Session["revenue"].ToString(), Session["CENTERDJ"].ToString(), Session["LOGINDJ"].ToString(), Session["PUBLICATIONDJ"].ToString());
                }
                else if (Session["FILTER"].ToString() == "D")
                {
                    if (ConfigurationSettings.AppSettings["agencyf2"].ToString() == "Y" && fla == "Y")
                        ds = bindagenname.bind10agency(compcode, userid, agency, Session["revenue"].ToString());
                    else
                        ds = bindagenname.bindagency(compcode, userid, agency, Session["revenue"].ToString());
                }

                else if (Session["FILTER"].ToString() == "P")
                {
                    if (ConfigurationSettings.AppSettings["agencyf2"].ToString() == "Y" && fla == "Y")
                        ds = bindagenname.bind10agency(compcode, userid, agency, Session["center"].ToString());
                    else
                        ds = bindagenname.bindagency(compcode, userid, agency, Session["center"].ToString());
                }
                else
                {
                    if (ConfigurationSettings.AppSettings["agencyf2"].ToString() == "Y" && fla == "Y")
                        ds = bindagenname.bind10agency(compcode, userid, agency, "0");
                    else
                        ds = bindagenname.bindagency(compcode, userid, agency, "0");
                }

            }
        //else
        //{
        //    NewAdbooking.classmysql.BookingMaster bindagenname = new NewAdbooking.classmysql.BookingMaster();
        //    if (Session["FILTER"].ToString() == "D")
        //    {
        //        ds = bindagenname.bindagency(compcode, userid, agency, Session["revenue"].ToString());
        //    }
        //    else
        //    {
        //        ds = bindagenname.bindagency(compcode, userid, agency, "0");
        //    }

        //}
        return ds;
    }

    ////////////////////////////add by anuja requirement for udyavani
    private void fillPubCenter(string compcode)
    {
        DataSet ds;
        if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "sql")
        {

            NewAdbooking.BillingClass.Classes.session_billing logindetail = new NewAdbooking.BillingClass.Classes.session_billing();
            ds = logindetail.getPubCenter();
        }
        else if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "orcl")
        {
            NewAdbooking.classesoracle.login logindetail = new NewAdbooking.classesoracle.login();

            ds = logindetail.getPubCenter_company(compcode);

        }
        else
        {
            NewAdbooking.classmysql.login logindetail = new NewAdbooking.classmysql.login();
            ds = logindetail.getPubCenter();
        }



        drprinting.Items.Clear();
        ListItem li1;



        li1 = new ListItem();
        li1.Text = "All";
        li1.Value = "All";
        li1.Selected = true;
        drprinting.Items.Add(li1);
        int i;
        for (i = 0; i < ds.Tables[0].Rows.Count; i++)
        {
            ListItem li;
            li = new ListItem();
            li.Text = ds.Tables[0].Rows[i].ItemArray[1].ToString();
            li.Value = ds.Tables[0].Rows[i].ItemArray[0].ToString();
            drprinting.Items.Add(li);
        }


    }
}
