// JScript File

// JScript File
var show="0";
var z=0;
var hiddentext;
// this variable is used foe storing value of autogenerated for session
var auto="";
var global_ds;
var row_num=0;
var glpubcode;
var glcentercode;
var gleditioncode;
var glsuppcode;
var glpageno;
var glddldaycode;
var hid_gau_cent;
var hid_gau_edi;
var hid_gau_pub;
var hid_gau_sup;

function fillcentercode(pub)
{
     document.getElementById("ddlEdition").options.length=1;
     document.getElementById("ddlEdition").value="0";
     document.getElementById("ddlSupplement").options.length=1;
     document.getElementById("ddlSupplement").value="0";
     var flaglayoutx=document.getElementById('hiddenlayoutx').value;
    if(typeof(pub)=="object")
    {
       var pubcode=pub.value;
    }
    else
    {
      var pubcode=pub;
    }
    if(pubcode !="0")
    {
        var compcode=document.getElementById('hiddencompcode').value;
        //var editioncode=document.getElementById('ddlEdition').value;
        var userid=document.getElementById('hiddenuserid').value;
        PaginationDays.addcentercode(compcode,userid,flaglayoutx,callbindcentercode); 
    }
      else
    {
      document.getElementById("ddlCenter").options.length=1;
      document.getElementById("ddlCenter").value="0";
      //document.getElementById("ddlEdition").options.length=1;
    //  document.getElementById("ddlEdition").value="0";
    //  document.getElementById("ddlSupplement").options.length=1;
     // document.getElementById("ddlSupplement").value="0";
    } 
}

function callbindcentercode(res)
{

var ds=res.value;
var pkgitem = document.getElementById("ddlCenter");
 
if(ds!= null && typeof(ds) == "object" && ds.Tables[0].Rows.length > 0) 
{
        var pkgitem=document.getElementById('ddlCenter');
         pkgitem.options[0]=new Option("------Select Center------","0");
     
//var pkgitem = document.getElementById("drpcity");
//alert(pkgitem);
    pkgitem.options.length = 1; 
    //alert(pkgitem.options.length);
    
    for (var i = 0  ; i < res.value.Tables[0].Rows.length; ++i)
    {
        pkgitem.options[pkgitem.options.length] = new Option(res.value.Tables[0].Rows[i].center,res.value.Tables[0].Rows[i].center_code);
        pkgitem.options.length;
       
    }
     if(hid_gau_cent==undefined || hid_gau_cent=="")
    {
      document.getElementById("ddlCenter").value="0";
    }
    else
    {
      document.getElementById("ddlCenter").value=hid_gau_cent;
      hid_gau_cent="";
    }
 //filledition();
}
return false;
}



function filledition(cent)
{
   
    document.getElementById("ddlSupplement").options.length=1;
    document.getElementById("ddlSupplement").value="0";
    var flaglayoutx=document.getElementById('hiddenlayoutx').value;
     if(typeof(cent)=="object")
    {
       var centercode=cent.value;
    }
    else
    {
      var centercode=cent;
    }
    
    if(centercode !="0")
    {
        //var centercode=document.getElementById('ddlCenter').value;
        var pubcode=document.getElementById('ddlPublication').value;
        var userid=document.getElementById('hiddenuserid').value;
        PaginationDays.addeditioncode(centercode,userid,pubcode,flaglayoutx,callbind); 
    }
      else
    {
      document.getElementById("ddlEdition").options.length=1;
      document.getElementById("ddlEdition").value="0";
    } 
    
//    var centercode=document.getElementById('ddlCenter').value;
//    var pubcode=document.getElementById('ddlPublication').value;
//    var userid=document.getElementById('hiddenuserid').value;
//     if(centercode=="0")
//    {
//    centercode=hid_gau_cent;
//    }
//    if(pubcode=="0")
//    {
//    pubcode=hid_gau_pub;
//    }
    // PaginationDays.addeditioncode(centercode,userid,pubcode,callbind); 
}

function callbind(res)
{

var ds=res.value;
var pkgitem = document.getElementById("ddlEdition");
 
if(ds!= null && typeof(ds) == "object" && ds.Tables[0].Rows.length > 0) 
{
    var pkgitem=document.getElementById('ddlEdition');
    pkgitem.options[0]=new Option("------Select Edititon------","0");
    //var pkgitem = document.getElementById("drpcity");
    //alert(pkgitem);
    pkgitem.options.length = 1; 
    //alert(pkgitem.options.length);
    for (var i = 0  ; i < res.value.Tables[0].Rows.length; ++i)
    {
        pkgitem.options[pkgitem.options.length] = new Option(res.value.Tables[0].Rows[i].edition_name,res.value.Tables[0].Rows[i].edition_code);
        
       pkgitem.options.length;
       
    }
    
     if(hid_gau_edi==undefined || hid_gau_edi=="")
    {
      document.getElementById("ddlEdition").value="0";
    }
    else
    {
      document.getElementById("ddlEdition").value=hid_gau_edi;
      hid_gau_edi="";
    }
 
}
else
{
    alert("There is No Matching value Found");
    pkgitem.options.length=1;
    //pkgitem.value="0";
    return false;
}
//if(global_ds !=null)
//{
//           document.getElementById('ddlPublication').value=global_ds.Tables[0].Rows[row_num].pub_code;
//           document.getElementById('ddlPublication').disabled=true; 
//           document.getElementById('ddlCenter').value=global_ds.Tables[0].Rows[row_num].center_code;
//           document.getElementById('ddlCenter').disabled=true;
//          
//           document.getElementById('ddlEdition').value=global_ds.Tables[0].Rows[row_num].edition_code;
//           document.getElementById('ddlEdition').disabled=true;
//           fillsupp();

//}
return false;
}


function fillsupp(edi)
{
    document.getElementById('ddlSupplement').value="0";
    document.getElementById('ddlSupplement').options.length="1";
    var flaglayoutx=document.getElementById('hiddenlayoutx').value;
     if(typeof(edi)=="object")
    {
       var editioncode=edi.value;
    }
    else
    {
      var editioncode=edi;
    }
    
    if(editioncode !="0")
    {
        var compcode=document.getElementById('hiddencompcode').value;
       // var editioncode=document.getElementById('ddlEdition').value;
        var userid=document.getElementById('hiddenuserid').value;
        PaginationDays.addsecpubcode(compcode,userid,editioncode,flaglayoutx,callbindsecpubcode); ; 
    }
      else
    {
      document.getElementById("ddlSupplement").options.length=1;
      document.getElementById("ddlSupplement").value="0";
    } 
//    document.getElementById('ddlSupplement').value="0";
//    document.getElementById('ddlSupplement').options.length="1";
//    var compcode=document.getElementById('hiddencompcode').value;
//    var editioncode=document.getElementById('ddlEdition').value;
//    var userid=document.getElementById('hiddenuserid').value;
//    PaginationDays.addsecpubcode(compcode,userid,editioncode,callbindsecpubcode); 
}

function callbindsecpubcode(res)
{

var ds=res.value;
var pkgitem = document.getElementById("ddlSupplement");
 
if(ds!= null && typeof(ds) == "object" && ds.Tables[0].Rows.length > 0) 
{
         var pkgitem=document.getElementById('ddlSupplement');
         pkgitem.options[0]=new Option("------Select Supplement------","0");
     
//var pkgitem = document.getElementById("drpcity");
//alert(pkgitem);
    pkgitem.options.length = 1; 
    //alert(pkgitem.options.length);
    for (var i = 0  ; i < res.value.Tables[0].Rows.length; ++i)
    {
        pkgitem.options[pkgitem.options.length] = new Option(res.value.Tables[0].Rows[i].supplement,res.value.Tables[0].Rows[i].supp_code);
        
       pkgitem.options.length;
       
    }
    
       if(hid_gau_sup==undefined || hid_gau_sup=="")
    {
      document.getElementById("ddlSupplement").value="0";
    }
    else
    {
      document.getElementById("ddlSupplement").value=hid_gau_sup;
      hid_gau_sup="";
    }
 
}

//if(global_ds !=null)
//{

//           document.getElementById('ddlSupplement').value=global_ds.Tables[0].Rows[row_num].sub_pub;
//           document.getElementById('ddlSupplement').disabled=true;
//}
return false;
}

function exitclick()
{
    if(confirm("Do You Want To Skip This Page"))
    {	
        window.close();
        return false;
    }
    return false;
}

  //click new button *********************************************************************
  function newClick()
    {
       //global_ds="";
       global_ds=null;
        show="1";
        document.getElementById('ddlDays').disabled = false;        
        document.getElementById('ddlPublication').disabled = false;
        document.getElementById('ddlCenter').disabled = false;
        document.getElementById('ddlEdition').disabled = false;
        document.getElementById('ddlSupplement').disabled = false;
        
        document.getElementById('txtPageno').disabled = false;
        document.getElementById('txtvalidfromdate').disabled=false;
        document.getElementById('txtvalidtodate').disabled=false;
       
       ////////////////////////////////////////////////////////////////////
        
        document.getElementById('ddlDays').value="0";
         document.getElementById('ddlDays').focus();
        document.getElementById('ddlPublication').value="0";
		document.getElementById('ddlCenter').value="0";
		document.getElementById('ddlEdition').value="0";			
		document.getElementById('ddlSupplement').value="0";				
		document.getElementById('txtPageno').value="";
		document.getElementById('txtvalidfromdate').value="";
		document.getElementById('txtvalidtodate').value="";
		document.getElementById('hiddenRecord_Id').value="";
		
		//document.getElementById('hiddentxt').value="";
        chkstatus(FlagStatus);
        document.getElementById('btnNew').disabled=true;
        document.getElementById('btnSave').disabled=false;
        document.getElementById('btnQuery').disabled=true;
			
		hiddentext="new";
		setButtonImages();	
		return false;
		
    }
    
    //cancel button click
    function cancelClick()
    {
        hiddentext="cancel";
        row_num=0;
        chkstatus(FlagStatus);
         
        document.getElementById('ddlDays').value="0";   		
		document.getElementById('ddlPublication').value="0";			
		document.getElementById('ddlCenter').value="0";			
		document.getElementById('ddlEdition').value="0";
	    document.getElementById('ddlSupplement').value="0";
		document.getElementById('ddlCenter').options.length="1";			
		document.getElementById('ddlEdition').options.length="1";
	    document.getElementById('ddlSupplement').options.length="1";	
		document.getElementById('txtPageno').value="";
		document.getElementById('txtvalidfromdate').value="";
		document.getElementById('txtvalidtodate').value="";
	    document.getElementById('hiddenRecord_Id').value="";
		
		//////////////////////////
        document.getElementById('ddlDays').disabled = true;
        document.getElementById('ddlPublication').disabled = true;
        document.getElementById('ddlCenter').disabled = true;
        document.getElementById('ddlEdition').disabled = true;
        document.getElementById('ddlSupplement').disabled = true;
        document.getElementById('txtPageno').disabled = true;
        document.getElementById('txtvalidfromdate').disabled=true;
        document.getElementById('txtvalidtodate').disabled=true;
       
       ////////////////////////////////////////////////////////////////////
        
		
		document.getElementById('btnNew').disabled=false;        
        if(document.getElementById('btnNew').disabled==false)
        {
	      document.getElementById('btnNew').focus();
        }    
        document.getElementById('btnSave').disabled=true;        
        document.getElementById('btnQuery').disabled=false;		
					
		document.getElementById('btnModify').disabled=true;			
		document.getElementById('btnExecute').disabled=true;
		
		document.getElementById('btnfirst').disabled=true;
			
		document.getElementById('btnprevious').disabled=true;
		document.getElementById('btnnext').disabled=true;
		document.getElementById('btnlast').disabled=true;
		//////////////////////////////////////////////////////////////////
		setButtonImages();	
		return false;
    }
    
    
       
    //Modify click---- Add by Rinki
    
    function ModifyClick()
{
         chkstatus(FlagStatus);
        hiddentext="modify";
        
        document.getElementById('ddlPublication').disabled=true;
        document.getElementById('ddlCenter').disabled=true;
        document.getElementById('ddlEdition').disabled=true;			
	    document.getElementById('ddlSupplement').disabled=true;				
        document.getElementById('ddlDays').disabled=true;
	    document.getElementById('txtPageno').disabled=false;
	    document.getElementById('txtvalidfromdate').disabled=true;
        document.getElementById('txtvalidtodate').disabled=true;
		  
        document.getElementById('btnSave').disabled = false;	
		/*document.getElementById('btnNew').disabled = true;	
		document.getElementById('btnQuery').disabled=true;
		document.getElementById('btnCancel').disabled = false;	
		document.getElementById('btnExit').disabled = false;	
		document.getElementById('btnModify').disabled=true;
		document.getElementById('btnfirst').disabled = true;	
		document.getElementById('btnnext').disabled = true;	
		document.getElementById('btnlast').disabled=true;
		document.getElementById('btnprevious').disabled=true;
		document.getElementById('btnDelete').disabled=true;
		document.getElementById('btnExecute').disabled=true;*/
       setButtonImages();
       return false;   
}

    //save button click ******************************************************************************
    //save click for save value in pagestatus master
function saveclick()
{
    auto=document.getElementById('hiddenauto').value;
    var dateformat=document.getElementById('hiddendateformat').value;
    var fromdate=document.getElementById('txtvalidfromdate').value;
    var todate=document.getElementById('txtvalidtodate').value;
    if(document.getElementById('ddlDays').value =="" || document.getElementById('ddlDays').value =="0")
     {
         alert("Please Select Pagination Day");
         document.getElementById('ddlDays').focus();
         return(false);
     }
  
    if(document.getElementById('ddlPublication').value=="" || document.getElementById('ddlPublication').value=="0")
     {
        alert("Please Select Publication ");
        document.getElementById('ddlPublication').focus();
        return false;
     }

     if(document.getElementById('ddlCenter').value =="" || document.getElementById('ddlCenter').value =="0")
     {
         alert("Please Select Printing Center");
         document.getElementById('ddlCenter').focus();
         return(false);
     }

     if(document.getElementById('ddlEdition').value == "" || document.getElementById('ddlEdition').value == "0")
     {
         alert("Please Select Edition");
         document.getElementById('ddlEdition').focus();
         return(false);
     }
           
     if(document.getElementById('ddlSupplement').value == "" || document.getElementById('ddlSupplement').value == "0")
     {
         alert("Please Select Supplement");
         document.getElementById('ddlSupplement').focus();
         return(false);
     }

     if(document.getElementById('txtPageno').value == "")
     {
         alert("Please Enter the Page Number.");
         document.getElementById('txtPageno').focus();
         return(false);
     }
     
            
     if(document.getElementById('txtvalidfromdate').value =="")
     {
          alert("Please Enter From Date");
          document.getElementById('txtvalidfromdate').focus();
          
          return(false);
     }
            
     if(document.getElementById('txtvalidtodate').value =="")
     {
           alert("Please Enter To Date");
           document.getElementById('txtvalidtodate').focus();
           return(false);
     }
     
     //********************************* check dateformat condition ---rinki---*******************//
             if(dateformat=="mm/dd/yyyy")
	        {
                var fromdate=document.getElementById('txtvalidfromdate').value;
                var todate=document.getElementById('txtvalidtodate').value;
	        }
        		
	        if(dateformat=="dd/mm/yyyy")
	        {
		        var txtfrom=fromdate.split("/");
		        var ddfrom=txtfrom[0];
		        var mmfrom=txtfrom[1];
		        var yyfrom=txtfrom[2];
		        fromdate=mmfrom+'/'+ddfrom+'/'+yyfrom;
        		
		        var txttill=todate.split("/");
		        var ddtill=txttill[0];
		        var mmtill=txttill[1];
		        var yytill=txttill[2];
		        todate=mmtill+'/'+ddtill+'/'+yytill;
	        }
	        if(dateformat=="yyyy/mm/dd")
	        {
		        var txtfrom=fromdate.split("/");
		        var yyfrom=txtfrom[0];
		        var mmfrom=txtfrom[1];
		        var ddfrom=txtfrom[2];
		        fromdate=mmfrom+'/'+ddfrom+'/'+yyfrom;
        		
		        var txttill=todate.split("/");
		        var yytill=txttill[0];
		        var mmtill=txttill[1];
		        var ddtill=txttill[2];
		        todate=mmtill+'/'+ddtill+'/'+yytill;
	        }
        	
	        var fdate=new Date(fromdate);
	        var tdate=new Date(todate);
        
        	if(fromdate !='' && todate !='' && fdate > tdate)
            {
	            alert("To Date Must Be Greater Than From Date");
	            document.getElementById('txtvalidtodate').focus();
	            return false;
            }					
            else if(fdate > tdate)
            {
            alert("From Date Should Be Less Than To Date");
            return false;
            }
            	

     //*********************************************************************************************//
//      if(document.getElementById('txtvalidfromdate').value > document.getElementById('txtvalidtodate').value)
//     {
//       alert("FromDate Can Not Be Greater Than ToDate");
//       return(false);
//     }

            var compcode=document.getElementById('hiddencompcode').value;
            var userid=document.getElementById('hiddenuserid').value;
            
			//save//
			var ddldaycode=document.getElementById('ddlDays').value;			
			var ddlpubcode=document.getElementById('ddlPublication').value;
			var ddlpubname=document.getElementById('ddlPublication').Text;
			var ddlcentercode=document.getElementById('ddlCenter').value;
			var ddlcentername=document.getElementById('ddlCenter').Text;
			var ddleditioncode=document.getElementById('ddlEdition').value;
			var ddleditionname=document.getElementById('ddlEdition').Text;
			var ddlsuppcode=document.getElementById('ddlSupplement').value;
			var ddlsuppname=document.getElementById('ddlSupplement').Text;			
						
			var ddlpgno=document.getElementById('txtPageno').value;
			
			//dan
	 var strtextd="";
     var  httpRequest =null;
     httpRequest= new XMLHttpRequest();
     if (httpRequest.overrideMimeType) {
          httpRequest.overrideMimeType('text/xml'); 
          }
          //httpRequest.onreadystatechange = function() {alertContents(httpRequest) };
 
            httpRequest.open( "GET","checksessiondan.aspx", false );
            httpRequest.send('');
            //alert(httpRequest.readyState);
            if (httpRequest.readyState == 4) 
            {
                //alert(httpRequest.status);
                if (httpRequest.status == 200) 
                {
                    strtextd=httpRequest.responseText;
                }
                else 
                {
                    //alert('There was a problem with the request.');
                    if(browser!="Microsoft Internet Explorer")
                    {
                        //alert(xmlObjMessage.childNodes[1].childNodes[21].childNodes[0].nodeValue);
                    }
                }
            }
              if(strtextd!="sess")
       {
       alert('Session Expired ! Please Login Again.');
       window.location.href="Login.aspx";
       return false;
       }           
						
			/*
			if(dateformat=="mm/dd/yyyy")
			{
			    var txtenrolldate=document.getElementById('txtenrolldate').value;
			}
			if(dateformat=="dd/mm/yyyy")
			{
			    var txt=document.getElementById('txtenrolldate').value;
			    var txt1=txt.split("/");
			    var dd=txt1[0];
			    var mm=txt1[1];
			    var yy=txt1[2];
			    var txtenrolldate=mm+'/'+dd+'/'+yy;
			}
			if(dateformat=="yyyy/mm/dd")
			{
			    var txt=document.getElementById('txtenrolldate').value;
			    var txt1=txt.split("/");
			    var yy=txt1[0];
			    var mm=txt1[1];
			    var dd=txt1[2];
			    var txtenrolldate=mm+'/'+dd+'/'+yy;
			}
			if(dateformat==null || dateformat=="" || dateformat=="undefined")
			{
			var txtenrolldate=document.getElementById('txtenrolldate').value;
			}
			
			
			if(dateformat=="mm/dd/yyyy")
			{
			var txtbussinessdate=document.getElementById('txtbusineedate').value;
			}
			if(dateformat=="dd/mm/yyyy")
			{
			var txt=document.getElementById('txtbusineedate').value;
			var txt1=txt.split("/");
			var dd=txt1[0];
			var mm=txt1[1];
			var yy=txt1[2];
			var txtbussinessdate=mm+'/'+dd+'/'+yy;
			}
			if(dateformat=="yyyy/mm/dd")
			{
			var txt=document.getElementById('txtbusineedate').value;
			var txt1=txt.split("/");
			var yy=txt1[0];
			var mm=txt1[1];
			var dd=txt1[2];
			var txtbussinessdate=mm+'/'+dd+'/'+yy;
			}
			if(dateformat==null || dateformat=="" || dateformat=="undefined")
			{
			var txtbussinessdate=document.getElementById('txtbusineedate').value;
			}
			*/
						
			/*
			if(document.getElementById('hiddenpermission').value=="5")
			{
			document.getElementById('btnQuery').disabled=true;
			document.getElementById('btnDelete').disabled=false;
			}
			else
			{
			}
			
			if(document.getElementById('hiddenpermission').value=="1")
			{
			document.getElementById('btnQuery').disabled=true;
			}
			else
			{
			
			}
			
			document.getElementById('btnDelete').disabled=true;
			if(document.getElementById('hiddenpermission').value=="2")
			{			
			    document.getElementById('btnDelete').disabled=true;			
			}
			else
			{
			
			}*/
			 if( hiddentext=="modify")
			 {
			    PaginationDays.UpdateDaysRecord(compcode,ddlpubcode,ddlcentercode,ddleditioncode,ddlsuppcode,ddlpgno,ddldaycode);
			    alert('Update Records successfully.');
			    updateStatus();
			     
			     global_ds.Tables[0].Rows[row_num].number_of_pages=document.getElementById('txtpageno').value;
		         document.getElementById('txtpageno').disabled=true;
		        document.getElementById('btnfirst').disabled=true;
                document.getElementById('btnprevious').disabled=true;
                setButtonImages();
			    return false;
			 }
			
			checkExistingRecord();
			//document.getElementById('btnSave').disabled=true;
			return false;
			
}
//********************************save ends***********************************
    
//check for existing entry
    function checkExistingRecord()
    {
        if(hiddentext=="new")
        {        
            var compcode=document.getElementById('hiddencompcode').value;
           // var userid=document.getElementById('hiddenuserid').value;
            var pubcode=document.getElementById('ddlPublication').value;
            var centercode=document.getElementById('ddlCenter').value;
            var editioncode=document.getElementById('ddlEdition').value;
            var suppcode=document.getElementById('ddlSupplement').value;
            var pageno=document.getElementById('txtPageno').value;
            var daycode=document.getElementById('ddlDays').value;
            PaginationDays.getvalues(compcode,pubcode,centercode,editioncode,suppcode,pageno,daycode,callbackEntryexists);            
        }

       // return false;
    }
    
    function callbackEntryexists(response)
    {
    var ds_1=response.value;
        if(ds_1==null)
            return false;
        if(ds_1.Tables[0].Rows.length!=0)
        {
            alert('Record already exists.');
            return false;
        }
        else
        {
            var compcode=document.getElementById('hiddencompcode').value;
            var userid=document.getElementById('hiddenuserid').value;
            
            var ddlpubcode=document.getElementById('ddlPublication').value;
            var ddlpubname=document.getElementById('ddlPublication').options[document.getElementById('ddlPublication').selectedIndex].text;
            
			var ddlcentercode=document.getElementById('ddlCenter').value;
			var ddlcentername=document.getElementById('ddlCenter').options[document.getElementById('ddlCenter').selectedIndex].text;
			
			var ddleditioncode=document.getElementById('ddlEdition').value;
			var ddleditionname=document.getElementById('ddlEdition').options[document.getElementById('ddlEdition').selectedIndex].text;		
			
			var ddlsuppcode=document.getElementById('ddlSupplement').value;
			var ddlsuppname=document.getElementById('ddlSupplement').options[document.getElementById('ddlSupplement').selectedIndex].text;						
						
			var ddlpgno=document.getElementById('txtPageno').value;
			var ddldaycode=document.getElementById('ddlDays').value;
			
			var txtvalidfromdate=document.getElementById('txtvalidfromdate').value;
			var txtvalidtodate=document.getElementById('txtvalidtodate').value;
			var dateformat=document.getElementById('hiddendateformat').value;
						
			PaginationDays.SaveDaysRecord(compcode,userid,ddlpubcode,ddlcentercode,ddleditioncode,ddlsuppcode,ddlpgno,ddldaycode,txtvalidfromdate,txtvalidtodate,/*ddlpubname,ddlcentername,ddleditionname,ddlsuppname*/dateformat);
			alert('Save Records successfully.');
        			
		    cancelClick();
		    setButtonImages();			
            return false;
        }
    }
    
    function queryclick()
    {
    
        chkstatus(FlagStatus);
        document.getElementById('btnQuery').disabled=true;
	    document.getElementById('btnExecute').disabled=false;
	    document.getElementById('btnSave').disabled=true;
        show="0";
        
        hiddentext="query";
        z=0;
        
        document.getElementById('hiddenstatuslabel').value="show";
        document.getElementById('ddlDays').value="0"; 
        document.getElementById('ddlPublication').value="0";			
		document.getElementById('ddlCenter').value="0";			
		document.getElementById('ddlEdition').value="0";			
        document.getElementById('ddlSupplement').value="0";			
		document.getElementById('txtPageno').value="";
		document.getElementById('txtvalidfromdate').value="";
		document.getElementById('txtvalidtodate').value="";
	    document.getElementById('hiddenRecord_Id').value="";
			//////////////////////////
       
        document.getElementById('ddlPublication').disabled = false;
        document.getElementById('ddlCenter').disabled = false;
        document.getElementById('ddlEdition').disabled = false;
        document.getElementById('ddlSupplement').disabled = false;
        document.getElementById('ddlDays').disabled = false;
        document.getElementById('txtPageno').disabled=false;
		document.getElementById('txtvalidfromdate').disabled=true;
		document.getElementById('txtvalidtodate').disabled=true;
	    document.getElementById('hiddenRecord_Id').disabled=false;
       
       ////////////////////////////////////////////////////////////////////
			
		/*document.getElementById('btnNew').disabled=true;
		document.getElementById('btnSave').disabled=true;
		document.getElementById('btnQuery').disabled=true;						
		document.getElementById('btnModify').disabled=true;			
		document.getElementById('btnfirst').disabled=true;
		document.getElementById('btnprevious').disabled=true;
		document.getElementById('btnnext').disabled=true;
		document.getElementById('btnlast').disabled=true;
		document.getElementById('btnDelete').disabled=true;
		document.getElementById('btnExecute').disabled=false;			
		document.getElementById('btnExit').disabled=false;*/
		document.getElementById('btnExecute').focus();
		setButtonImages();
		return false;
    }
    
    //Execute query
    function Executeclick()
    {
        if(hiddentext="query")
        {            
            var compcode=document.getElementById('hiddencompcode').value;           
            var pubcode=document.getElementById('ddlPublication').value;
            var centercode=document.getElementById('ddlCenter').value;
            var editioncode=document.getElementById('ddlEdition').value;
            var suppcode=document.getElementById('ddlSupplement').value;
            var pageno=document.getElementById('txtPageno').value;
            var ddldaycode=document.getElementById('ddlDays').value;  
            var dateformat=document.getElementById('hiddendateformat').value;  
            
            glpubcode= document.getElementById('ddlPublication').value;
            glcentercode=document.getElementById('ddlCenter').value;
            gleditioncode=document.getElementById('ddlEdition').value;
            glsuppcode=document.getElementById('ddlSupplement').value;
            glpageno=document.getElementById('txtPageno').value;
            glddldaycode=document.getElementById('ddlDays').value; 
            		
            				//dan
     var strtextd="";
     var  httpRequest =null;
     httpRequest= new XMLHttpRequest();
     if (httpRequest.overrideMimeType) {
          httpRequest.overrideMimeType('text/xml'); 
          }
          //httpRequest.onreadystatechange = function() {alertContents(httpRequest) };
 
            httpRequest.open( "GET","checksessiondan.aspx", false );
            httpRequest.send('');
            //alert(httpRequest.readyState);
            if (httpRequest.readyState == 4) 
            {
                //alert(httpRequest.status);
                if (httpRequest.status == 200) 
                {
                    strtextd=httpRequest.responseText;
                }
                else 
                {
                    //alert('There was a problem with the request.');
                    if(browser!="Microsoft Internet Explorer")
                    {
                        //alert(xmlObjMessage.childNodes[1].childNodes[21].childNodes[0].nodeValue);
                    }
                }
            }
              if(strtextd!="sess")
       {
       alert('Session Expired ! Please Login Again.');
       window.location.href="Login.aspx";
       return false;
       }           
           
            PaginationDays.ExecuteDaysRecord(compcode,pubcode,centercode,editioncode,suppcode,pageno,ddldaycode,dateformat,callbackExecuteRecord);
            updateStatus();
            setButtonImages();
            return false;
        }
    }
    
    
     //execute record's store in global dataset
    function callbackExecuteRecord(response)
    {
    global_ds=response.value;
        if(global_ds==null)
            return false;
            
        if(global_ds.Tables[0].Rows.length==0)
        {
           alert("This Search Criteria Does Not Exist.");
           cancelClick();
            return false;
        }
         if(global_ds.Tables[0].Rows.length!=0)
         {
           document.getElementById('btnExecute').disabled=true;
           document.getElementById('btnModify').disabled=false;
           document.getElementById('btnDelete').disabled=false;
    
           document.getElementById('ddlPublication').value=global_ds.Tables[0].Rows[0].pub_code;
           document.getElementById('ddlPublication').disabled=true; 
           hid_gau_cent=global_ds.Tables[0].Rows[0].center_code;
           hid_gau_edi=global_ds.Tables[0].Rows[0].edition_code;
           hid_gau_sup=global_ds.Tables[0].Rows[0].sub_pub;

           fillcentercode(global_ds.Tables[0].Rows[0].pub_code);
           //document.getElementById('ddlCenter').value=global_ds.Tables[0].Rows[0].center_code;
           document.getElementById('ddlCenter').disabled=true;
           filledition(global_ds.Tables[0].Rows[0].center_code);
          // document.getElementById('ddlEdition').value=global_ds.Tables[0].Rows[0].edition_code;
           document.getElementById('ddlEdition').disabled=true;
           fillsupp(global_ds.Tables[0].Rows[0].edition_code);
           //document.getElementById('ddlSupplement').value=global_ds.Tables[0].Rows[0].sub_pub;
           document.getElementById('ddlSupplement').disabled=true;
           
           document.getElementById('txtPageno').value=global_ds.Tables[0].Rows[0].number_of_pages;
           document.getElementById('txtPageno').disabled=true;
           document.getElementById('ddlDays').value=global_ds.Tables[0].Rows[0].pub_day;
             document.getElementById('ddlDays').disabled=true;
           /*if(global_ds.Tables[0].Rows[0].pub_day=='MON')
              document.getElementById('ddlDays').value="Monday";
           else if(global_ds.Tables[0].Rows[0].pub_day=='TUE')     
                    document.getElementById('ddlDays').value="Tuesday";
           else if(global_ds.Tables[0].Rows[0].pub_day=='WED')     
                    document.getElementById('ddlDays').value="Wednesday";
           else if(global_ds.Tables[0].Rows[0].pub_day=='THU')     
                    document.getElementById('ddlDays').value="Thursday";
           else if(global_ds.Tables[0].Rows[0].pub_day=='FRI')     
                    document.getElementById('ddlDays').value="Friday";
           else if(global_ds.Tables[0].Rows[0].pub_day=='SAT')     
                    document.getElementById('ddlDays').value="Saturday";
           else if(global_ds.Tables[0].Rows[0].pub_day=='SUN')     
                    document.getElementById('ddlDays').value="Sunday";*/
                             
           //document.getElementById('ddlDays').value=global_ds.Tables[0].Rows[0].pub_day;
           document.getElementById('hiddenRecord_Id').value=global_ds.Tables[0].Rows[0].record_id;
           document.getElementById('hiddenRecord_Id').disabled=true;
           document.getElementById('txtvalidfromdate').value=global_ds.Tables[0].Rows[0].valid_date_from;
           document.getElementById('txtvalidfromdate').disabled=true;
           document.getElementById('txtvalidtodate').value=global_ds.Tables[0].Rows[0].valid_date_to;            
            document.getElementById('txtvalidtodate').disabled=true;        
         }
         
         if(global_ds.Tables[0].Rows.length==1)
         {
            //document.getElementById('btnModify').disabled=false;
           // alert(global_ds.Tables[0].Rows.length);
            document.getElementById('btnfirst').disabled=true;
            document.getElementById('btnprevious').disabled=true;
            document.getElementById('btnnext').disabled=true;
            document.getElementById('btnlast').disabled=true;
         }
         else
         {
             if(row_num==0)
             {//alert(row_num);
               // document.getElementById('btnModify').disabled=false;
                document.getElementById('btnQuery').disabled=false;
                document.getElementById('btnfirst').disabled=true;
                document.getElementById('btnprevious').disabled=true;
                document.getElementById('btnnext').disabled=false;
                document.getElementById('btnlast').disabled=false;
             }
             else if(row_num==global_ds.Tables[0].Rows.length)
            {
                document.getElementById('btnfirst').disabled=false;
                document.getElementById('btnprevious').disabled=false;
                document.getElementById('btnnext').disabled=true;
                document.getElementById('btnlast').disabled=true;
            }
            
            else
            {
                document.getElementById('btnfirst').disabled=false;
                document.getElementById('btnprevious').disabled=false;
                document.getElementById('btnnext').disabled=false;
                document.getElementById('btnlast').disabled=false;
            }
          }
           
          if(document.getElementById('btnModify').disabled==false)
    	  {
      	    document.getElementById('btnModify').focus();
      	    
		  }
          setButtonImages();   
    }
    
    function bind_controls()
    {
           document.getElementById('ddlPublication').value=global_ds.Tables[0].Rows[row_num].pub_code; 
           hid_gau_cent=global_ds.Tables[0].Rows[row_num].center_code;
           hid_gau_edi=global_ds.Tables[0].Rows[row_num].edition_code;
           hid_gau_sup=global_ds.Tables[0].Rows[row_num].sub_pub;
           fillcentercode(global_ds.Tables[0].Rows[row_num].pub_code);
           
          // document.getElementById('ddlCenter').value=global_ds.Tables[0].Rows[row_num].center_code;
           filledition(global_ds.Tables[0].Rows[row_num].center_code);
//           document.getElementById('ddlEdition').value=global_ds.Tables[0].Rows[row_num].edition_code;
//           document.getElementById('ddlSupplement').value=global_ds.Tables[0].Rows[row_num].sub_pub;
           fillsupp(global_ds.Tables[0].Rows[row_num].edition_code);
           document.getElementById('txtPageno').value=global_ds.Tables[0].Rows[row_num].number_of_pages;
           document.getElementById('ddlDays').value=global_ds.Tables[0].Rows[row_num].pub_day;
         /* if(global_ds.Tables[0].Rows[row_num].pub_day=='MON')
              document.getElementById('ddlDays').value="Monday";
           else if(global_ds.Tables[0].Rows[row_num].pub_day=='TUE')     
                    document.getElementById('ddlDays').value="Tuesday";
           else if(global_ds.Tables[0].Rows[row_num].pub_day=='WED')     
                    document.getElementById('ddlDays').value="Wednesday";
           else if(global_ds.Tables[0].Rows[row_num].pub_day=='THU')     
                    document.getElementById('ddlDays').value="Thursday";
           else if(global_ds.Tables[0].Rows[row_num].pub_day=='FRI')     
                    document.getElementById('ddlDays').value="Friday";
           else if(global_ds.Tables[0].Rows[row_num].pub_day=='SAT')     
                    document.getElementById('ddlDays').value="Saturday";
           else if(global_ds.Tables[0].Rows[row_num].pub_day=='SUN')     
                    document.getElementById('ddlDays').value="Sunday";*/
           
           document.getElementById('txtvalidfromdate').value=global_ds.Tables[0].Rows[row_num].valid_date_from;
           document.getElementById('txtvalidtodate').value=global_ds.Tables[0].Rows[row_num].valid_date_to; 
           document.getElementById('hiddenRecord_Id').value=global_ds.Tables[0].Rows[row_num].record_id;
    }
    
    //****************Navigate to first record*****************************   
function adFirst()
{
    document.getElementById('btnfirst').disabled=true;
    document.getElementById('btnprevious').disabled=true;
    document.getElementById('btnnext').disabled=false;
    document.getElementById('btnlast').disabled=false;
    
    row_num=0;    

    bind_controls();    
     
          if(document.getElementById('btnModify').disabled==false)
    	  {
      	    document.getElementById('btnModify').focus();
		  }
    updateStatus();
    document.getElementById('btnfirst').disabled=true;
    document.getElementById('btnprevious').disabled=true; 
    setButtonImages();
    return false;
}

    
    //****************Navigate to last record *****************************
function adLast()
{
    document.getElementById('btnfirst').disabled=false;
    document.getElementById('btnprevious').disabled=false;
    document.getElementById('btnnext').disabled=true;
    document.getElementById('btnlast').disabled=true;
    
    row_num=global_ds.Tables[0].Rows.length-1;    

    bind_controls();  
     
          if(document.getElementById('btnModify').disabled==false)
    	  {
      	    document.getElementById('btnModify').focus();
		  } 
		  setButtonImages();
		  return false; 
}

//****************Navigate to previous record *****************************
function adPrevious()
{
    row_num=row_num-1;
    
     document.getElementById('btnnext').disabled=false;
    document.getElementById('btnlast').disabled=false;
    document.getElementById('btnfirst').disabled=true;
    document.getElementById('btnprevious').disabled=true;

    if(row_num>=0)
     updateStatus();
       bind_controls();  
        
          if(document.getElementById('btnModify').disabled==false)
    	  {
      	    document.getElementById('btnModify').focus();
		  }   
   
    
    row_num=row_num-1;
    if(row_num>=0)
    {
        row_num=row_num+1;
        setButtonImages();
        return false;
    }
    else
    {
        document.getElementById('btnnext').disabled=false;
		document.getElementById('btnlast').disabled=false;
		document.getElementById('btnfirst').disabled=true;
		document.getElementById('btnprevious').disabled=true;
        row_num=row_num+1;
    }
    setButtonImages();
    return false;   
}

//****************Navigate to next record******************************
function adNext()
{
    row_num=row_num+1;    
    document.getElementById('btnprevious').disabled=false;
    document.getElementById('btnfirst').disabled=false;
    
    if(row_num<global_ds.Tables[0].Rows.length)
       bind_controls();
     
          if(document.getElementById('btnModify').disabled==false)
    	  {
      	    document.getElementById('btnModify').focus();
		  }
    row_num=row_num+1;
    if(row_num<global_ds.Tables[0].Rows.length)
    {
        row_num=row_num-1;
        updateStatus();
        setButtonImages();
        document.getElementById('btnnext').disabled=false;
        document.getElementById('btnlast').disabled=false;
        document.getElementById('btnfirst').disabled=false;
        document.getElementById('btnprevious').disabled=false;
        return false;
    }
    else
    {
       document.getElementById('btnnext').disabled=true;
	   document.getElementById('btnlast').disabled=true;
	   document.getElementById('btnfirst').disabled=false;
	   document.getElementById('btnprevious').disabled=false;
        row_num=row_num-1;
        return false;
    }
    if(document.getElementById('btnModify').disabled==false)
       document.getElementById('btnModify').focus();
    return false;
}

function DeleteClick()
{
    var compcode=document.getElementById('hiddencompcode').value;
    var pub=document.getElementById('ddlPublication').value;
    var pubcenter=document.getElementById('ddlCenter').value;
    var edition=document.getElementById('ddlEdition').value;
    var supp=document.getElementById('ddlSupplement').value; 
    var dday=document.getElementById('ddlDays').value;     
    var pgnumber=document.getElementById('txtpageno').value;
     var dateformat=document.getElementById('hiddendateformat').value;  
            
   // var rec_id=document.getElementById('hiddenRecord_Id').value;
   //dan
     var strtextd="";
     var  httpRequest =null;
     httpRequest= new XMLHttpRequest();
     if (httpRequest.overrideMimeType) {
          httpRequest.overrideMimeType('text/xml'); 
          }
          //httpRequest.onreadystatechange = function() {alertContents(httpRequest) };
 
            httpRequest.open( "GET","checksessiondan.aspx", false );
            httpRequest.send('');
            //alert(httpRequest.readyState);
            if (httpRequest.readyState == 4) 
            {
                //alert(httpRequest.status);
                if (httpRequest.status == 200) 
                {
                    strtextd=httpRequest.responseText;
                }
                else 
                {
                    //alert('There was a problem with the request.');
                    if(browser!="Microsoft Internet Explorer")
                    {
                        //alert(xmlObjMessage.childNodes[1].childNodes[21].childNodes[0].nodeValue);
                    }
                }
            }
              if(strtextd!="sess")
       {
       alert('Session Expired ! Please Login Again.');
       window.location.href="Login.aspx";
       return false;
       }           
    
    if(confirm('Are You sure ! Do you want delete this record ?.'))
    {
       PaginationDays.DeleteDaysRecord(compcode,pub,pubcenter,edition,supp,dday,pgnumber)
        alert('Record deleted successfully.');
  
       PaginationDays.ExecuteDaysRecord(compcode,glpubcode,glcentercode,gleditioncode,glsuppcode,glpageno,glddldaycode,dateformat,delcall);
    }
    else
	{  
	   	setButtonImages(); 
	   return false;
	}

    cancelClick();
    setButtonImages();
    return false;
}
    
    function delcall(res)
{
	 global_ds=res.value;
	len=global_ds.Tables[0].Rows.length;
	var userid=document.getElementById('hiddenuserid').value;
	if(global_ds.Tables[0].Rows.length==0)
	{
		alert("No More Data is here to be deleted");
        document.getElementById('hiddencompcode').value="";
        document.getElementById('ddlPublication').value="";
        document.getElementById('ddlCenter').value="";
        document.getElementById('ddlEdition').value="";
        document.getElementById('ddlSupplement').value=""; 
        document.getElementById('ddlDays').value="";     
        document.getElementById('txtpageno').value="";
        document.getElementById('hiddenRecord_Id').value="";
	    return false;
	}
	else if(z>=len || z==-1)
	{
		   document.getElementById('ddlPublication').value=global_ds.Tables[0].Rows[0].pub_code;
           document.getElementById('ddlPublication').disabled=true; 
           
           hid_gau_cent=global_ds.Tables[0].Rows[0].center_code;
           hid_gau_edi=global_ds.Tables[0].Rows[0].edition_code;
           hid_gau_sup=global_ds.Tables[0].Rows[0].sub_pub;
           
           fillcentercode(global_ds.Tables[0].Rows[0].pub_code);
           document.getElementById('ddlCenter').disabled=true;
              //***************************************************************************************//
           /* var res =PaginationDays.addeditioncode(global_ds.Tables[0].Rows[0].center_code,userid,global_ds.Tables[0].Rows[0].pub_code); 
            var ds=res.value;
            var pkgitem = document.getElementById("ddlEdition");
             
            if(ds!= null && typeof(ds) == "object" && ds.Tables[0].Rows.length > 0) 
            {
                    var pkgitem=document.getElementById('ddlEdition');
                    pkgitem.options[0]=new Option("------Select Edititon------","0");
                    pkgitem.options.length = 1; 
                    
                    for (var i = 0  ; i < res.value.Tables[0].Rows.length; ++i)
                   {
                       pkgitem.options[pkgitem.options.length] = new Option(res.value.Tables[0].Rows[i].edition_name,res.value.Tables[0].Rows[i].edition_code);
                       pkgitem.options.length;
                   }
             
            }*/
           //****************************************************//
           filledition(global_ds.Tables[0].Rows[0].center_code);
           document.getElementById('ddlEdition').disabled=true;
          // document.getElementById('ddlSupplement').value=global_ds.Tables[0].Rows[0].sub_pub;
           fillsupp(global_ds.Tables[0].Rows[0].edition_code);
           document.getElementById('ddlSupplement').disabled=true;
           
           document.getElementById('txtpageno').value=global_ds.Tables[0].Rows[0].number_of_pages;
           document.getElementById('txtpageno').disabled=true;
           document.getElementById('ddlDays').value=global_ds.Tables[0].Rows[0].pub_day;
           document.getElementById('ddlDays').disabled=true;
           document.getElementById('hiddenRecord_Id').value=global_ds.Tables[0].Rows[0].record_id;
           document.getElementById('hiddenRecord_Id').disabled=true;
           document.getElementById('txtvalidfromdate').value=global_ds.Tables[0].Rows[0].valid_date_from;
           document.getElementById('txtvalidfromdate').disabled=true;
           document.getElementById('txtvalidtodate').value=global_ds.Tables[0].Rows[0].valid_date_to;            
           document.getElementById('txtvalidtodate').disabled=true;    
	
    }
    else
	{
	       
           	       
		   document.getElementById('ddlPublication').value=global_ds.Tables[0].Rows[z].pub_code;
           document.getElementById('ddlPublication').disabled=true; 
           
           hid_gau_cent=global_ds.Tables[0].Rows[0].center_code;
           hid_gau_edi=global_ds.Tables[0].Rows[0].edition_code;
           hid_gau_sup=global_ds.Tables[0].Rows[0].sub_pub;
           
           fillcentercode(global_ds.Tables[0].Rows[z].pub_code);
           //document.getElementById('ddlCenter').value=global_ds.Tables[0].Rows[z].center_code;
           document.getElementById('ddlCenter').disabled=true;
             //***************************************************************************************//
            /*var res =PaginationDays.addeditioncode(global_ds.Tables[0].Rows[z].center_code,userid,global_ds.Tables[0].Rows[z].pub_code); 
            var ds=res.value;
            var pkgitem = document.getElementById("ddlEdition");
             
            if(ds!= null && typeof(ds) == "object" && ds.Tables[0].Rows.length > 0) 
            {
                    var pkgitem=document.getElementById('ddlEdition');
                    pkgitem.options[0]=new Option("------Select Edititon------","0");
                    pkgitem.options.length = 1; 
                    
                    for (var i = 0  ; i < res.value.Tables[0].Rows.length; ++i)
                   {
                       pkgitem.options[pkgitem.options.length] = new Option(res.value.Tables[0].Rows[i].edition_name,res.value.Tables[0].Rows[i].edition_code);
                       pkgitem.options.length;
                   }
             
            }*/
           //****************************************************//
           //document.getElementById('ddlEdition').value=global_ds.Tables[0].Rows[z].edition_code;
           filledition(global_ds.Tables[0].Rows[z].center_code);
           document.getElementById('ddlEdition').disabled=true;
           //document.getElementById('ddlSupplement').value=global_ds.Tables[0].Rows[z].sub_pub;
           fillsupp(global_ds.Tables[0].Rows[z].edition_code);
           document.getElementById('ddlSupplement').disabled=true;
           document.getElementById('txtpageno').value=global_ds.Tables[0].Rows[z].number_of_pages;
           document.getElementById('txtpageno').disabled=true;
           document.getElementById('ddlDays').value=global_ds.Tables[0].Rows[z].pub_day;
           document.getElementById('ddlDays').disabled=true;
            document.getElementById('hiddenRecord_Id').value=global_ds.Tables[0].Rows[z].record_id;
           document.getElementById('hiddenRecord_Id').disabled=true;
           document.getElementById('txtvalidfromdate').value=global_ds.Tables[0].Rows[z].valid_date_from;
           document.getElementById('txtvalidfromdate').disabled=true;
           document.getElementById('txtvalidtodate').value=global_ds.Tables[0].Rows[z].valid_date_to;            
           document.getElementById('txtvalidtodate').disabled=true;    
	
					
           
           ///////////////////////////////////////////
	}
	        if (z==0)
               {
                updateStatus();
                document.getElementById('btnfirst').disabled=true;
                document.getElementById('btnprevious').disabled=true;
                }

             if(z==global_ds.Tables[0].Rows.length)
              {
                 updateStatus();
              }       
		
   	setButtonImages(); 
   return false;
}

function ClientisNumber()
{
	if ((event.keyCode>=48 && event.keyCode<=57)||(event.keyCode==9)||(event.keyCode==11))
	{
		
		return true;
	}
	else
	{
		return false;
	}
	
}

function setButtonImages()
{
    if(document.getElementById('btnNew').disabled==true)
        document.getElementById('btnNew').src="btimages/new-off.jpg";
    else
        document.getElementById('btnNew').src="btimages/new.jpg";
        
    if(document.getElementById('btnSave').disabled==true)
        document.getElementById('btnSave').src="btimages/save-off.jpg";
    else
        document.getElementById('btnSave').src="btimages/save.jpg";
        
    if(document.getElementById('btnModify').disabled==true)
        document.getElementById('btnModify').src="btimages/modify-off.jpg";
    else
        document.getElementById('btnModify').src="btimages/modify.jpg";
        
    if(document.getElementById('btnQuery').disabled==true)
        document.getElementById('btnQuery').src="btimages/query-off.jpg";
    else
        document.getElementById('btnQuery').src="btimages/query.jpg";
    
    if(document.getElementById('btnExecute').disabled==true)
        document.getElementById('btnExecute').src="btimages/execute-off.jpg";
    else
        document.getElementById('btnExecute').src="btimages/execute.jpg";
        
    if(document.getElementById('btnCancel').disabled==true)
        document.getElementById('btnCancel').src="btimages/clear-off.jpg";
    else
        document.getElementById('btnCancel').src="btimages/clear.jpg";
        
    if(document.getElementById('btnfirst').disabled==true)
        document.getElementById('btnfirst').src="btimages/first-off.jpg";
    else
        document.getElementById('btnfirst').src="btimages/first.jpg";
        
    if(document.getElementById('btnprevious').disabled==true)
        document.getElementById('btnprevious').src="btimages/previous-off.jpg";
    else
        document.getElementById('btnprevious').src="btimages/previous.jpg";
        
    if(document.getElementById('btnnext').disabled==true)
        document.getElementById('btnnext').src="btimages/next-off.jpg";
    else
        document.getElementById('btnnext').src="btimages/next.jpg";
        
    if(document.getElementById('btnlast').disabled==true)
        document.getElementById('btnlast').src="btimages/last-off.jpg";
    else
        document.getElementById('btnlast').src="btimages/last.jpg";   
        
    if(document.getElementById('btnDelete').disabled==true)
        document.getElementById('btnDelete').src="btimages/delete-off.jpg";
    else
        document.getElementById('btnDelete').src="btimages/delete.jpg";
        
    if(document.getElementById('btnExit').disabled==true)
        document.getElementById('btnExit').src="btimages/exit-off.jpg";
    else
        document.getElementById('btnExit').src="btimages/exit.jpg";
}

function changebackcolor(e)
{
  var idfocus="";
  var idfoc=e.id;
  if(idfocus!="")
  {
      document.getElementById(idfocus).style.backgroundColor="";
  }
      document.getElementById(idfoc).style.backgroundColor="#FFFF80";
      
      idfocus=e.id;
    
}

function chkstatus(FlagStatus)
{
	if(FlagStatus==0||FlagStatus==8)
		{
			document.getElementById('btnNew').disabled=true;
			document.getElementById('btnQuery').disabled=true;
			document.getElementById('btnDelete').disabled=true;	
			document.getElementById('btnSave').disabled=true;	
			document.getElementById('btnExecute').disabled=true;
			document.getElementById('btnCancel').disabled=true;
			document.getElementById('btnModify').disabled=true;		
			
			document.getElementById('btnfirst').disabled=true;				
			document.getElementById('btnnext').disabled=true;					
			document.getElementById('btnprevious').disabled=true;			
			document.getElementById('btnlast').disabled=true;			
			document.getElementById('btnExit').disabled=true;	
			alert("You Are Not Authorised To See This Form");
			return false;
					
		}
		if(FlagStatus==1||FlagStatus==9)
		{
			document.getElementById('btnNew').disabled=true;
			document.getElementById('btnQuery').disabled=true;
			document.getElementById('btnDelete').disabled=true;	
			document.getElementById('btnSave').disabled=false;	
			document.getElementById('btnExecute').disabled=true;
			document.getElementById('btnCancel').disabled=false;
			document.getElementById('btnModify').disabled=true;		
			
			document.getElementById('btnfirst').disabled=true;				
			document.getElementById('btnnext').disabled=true;					
			document.getElementById('btnprevious').disabled=true;			
			document.getElementById('btnlast').disabled=true;			
			document.getElementById('btnExit').disabled=false;	
			return false;
		}
		if(FlagStatus==2||FlagStatus==10)
		{
			document.getElementById('btnExecute').disabled=false;
			document.getElementById('btnQuery').disabled=true;
			document.getElementById('btnDelete').disabled=true;
			document.getElementById('btnNew').disabled=true;
			document.getElementById('btnCancel').disabled=false;
			document.getElementById('btnExecute').disabled=true;
			document.getElementById('btnModify').disabled=true;		
			document.getElementById('btnExit').disabled=false;		
			
			document.getElementById('btnSave').disabled=true;
			document.getElementById('btnfirst').disabled=true;				
			document.getElementById('btnnext').disabled=true;					
			document.getElementById('btnprevious').disabled=true;			
			document.getElementById('btnlast').disabled=true;			
			document.getElementById('btnExit').disabled=false;	
			return false;
		
		}
		
		if(FlagStatus==3||FlagStatus==11)
		{
			document.getElementById('btnNew').disabled=true;
			document.getElementById('btnQuery').disabled=true;
			document.getElementById('btnExecute').disabled=true;
			document.getElementById('btnDelete').disabled=true;
			document.getElementById('btnCancel').disabled=false;		
			document.getElementById('btnExit').disabled=false;		
			
			
			document.getElementById('btnModify').disabled=true;		
			
			document.getElementById('btnSave').disabled=false;
			document.getElementById('btnfirst').disabled=true;				
			document.getElementById('btnnext').disabled=true;					
			document.getElementById('btnprevious').disabled=true;			
			document.getElementById('btnlast').disabled=true;		
		}
		
		if(FlagStatus==4||FlagStatus==12)
		{
			document.getElementById('btnNew').disabled=true;
			document.getElementById('btnExecute').disabled=true;
			document.getElementById('btnDelete').disabled=true;
			document.getElementById('btnCancel').disabled=false;		
			document.getElementById('btnExit').disabled=false;		
			
			
			document.getElementById('btnModify').disabled=true;		
			
			document.getElementById('btnSave').disabled=true;
			document.getElementById('btnfirst').disabled=true;				
			document.getElementById('btnnext').disabled=true;					
			document.getElementById('btnprevious').disabled=true;			
			document.getElementById('btnlast').disabled=true;		
		}
		if(FlagStatus==5||FlagStatus==13)
		{
			document.getElementById('btnNew').disabled=true;
			document.getElementById('btnExecute').disabled=true;
			document.getElementById('btnDelete').disabled=true;
			document.getElementById('btnCancel').disabled=false;		
			document.getElementById('btnExit').disabled=false;		
			
			
			document.getElementById('btnModify').disabled=true;		
			
			document.getElementById('btnSave').disabled=true;
			document.getElementById('btnfirst').disabled=true;				
			document.getElementById('btnnext').disabled=true;					
			document.getElementById('btnprevious').disabled=true;			
			document.getElementById('btnlast').disabled=true;		
		}
		if(FlagStatus==6||FlagStatus==14)
		{
			document.getElementById('btnNew').disabled=true;
			document.getElementById('btnExecute').disabled=true;
			document.getElementById('btnDelete').disabled=true;
			document.getElementById('btnCancel').disabled=false;		
			document.getElementById('btnExit').disabled=false;		
			
			
			document.getElementById('btnModify').disabled=true;		
			
			document.getElementById('btnSave').disabled=true;
			document.getElementById('btnfirst').disabled=true;				
			document.getElementById('btnnext').disabled=true;					
			document.getElementById('btnprevious').disabled=true;			
			document.getElementById('btnlast').disabled=true;		
		}
		if(FlagStatus==7||FlagStatus==15)
		{
			document.getElementById('btnNew').disabled=true;
			document.getElementById('btnExecute').disabled=true;
			document.getElementById('btnDelete').disabled=true;
			document.getElementById('btnCancel').disabled=false;		
			document.getElementById('btnExit').disabled=false;		
			
			
			document.getElementById('btnModify').disabled=true;		
			
			document.getElementById('btnSave').disabled=false;
			document.getElementById('btnfirst').disabled=true;				
			document.getElementById('btnnext').disabled=true;					
			document.getElementById('btnprevious').disabled=true;			
			document.getElementById('btnlast').disabled=true;		
		}
	return false;
}

function updateStatus()
{
    FlagStatus=7;
	chkstatus(FlagStatus);
	if(FlagStatus==2||FlagStatus==3)
	{
		document.getElementById('btnQuery').disabled=false;
		document.getElementById('btnExecute').disabled=true;
		document.getElementById('btnSave').disabled=true;
		document.getElementById('btnModify').disabled=false;
		document.getElementById('btnfirst').disabled=false;				
		document.getElementById('btnnext').disabled=false;					
		document.getElementById('btnprevious').disabled=false;			
		document.getElementById('btnlast').disabled=false;
		document.getElementById('btnDelete').disabled=true;
	}
	if(FlagStatus==4)
	{
		document.getElementById('btnDelete').disabled=false;
		document.getElementById('btnExecute').disabled=true;
		document.getElementById('btnSave').disabled=true;
		document.getElementById('btnQuery').disabled=false;
		document.getElementById('btnModify').disabled=true;
		document.getElementById('btnfirst').disabled=false;				
		document.getElementById('btnnext').disabled=false;					
		document.getElementById('btnprevious').disabled=false;			
		document.getElementById('btnlast').disabled=false;
	
	}
	if(FlagStatus==5)
	{
		document.getElementById('btnDelete').disabled=false;
		document.getElementById('btnExecute').disabled=true;
		document.getElementById('btnSave').disabled=true;
		document.getElementById('btnQuery').disabled=false;
		document.getElementById('btnModify').disabled=true;
		document.getElementById('btnfirst').disabled=false;				
		document.getElementById('btnnext').disabled=false;					
		document.getElementById('btnprevious').disabled=false;			
		document.getElementById('btnlast').disabled=false;
		
	}
	if(FlagStatus==6||FlagStatus==7)
	{
		document.getElementById('btnDelete').disabled=false;
		document.getElementById('btnExecute').disabled=true;
		document.getElementById('btnSave').disabled=true;
		document.getElementById('btnQuery').disabled=false;
		document.getElementById('btnModify').disabled=false;
		document.getElementById('btnfirst').disabled=false;				
		document.getElementById('btnnext').disabled=false;					
		document.getElementById('btnprevious').disabled=false;			
		document.getElementById('btnlast').disabled=false;
		
	}
	if(FlagStatus==1 || FlagStatus==0)
	{
		document.getElementById('btnDelete').disabled=true;
		document.getElementById('btnExecute').disabled=true;
		document.getElementById('btnSave').disabled=true;
		document.getElementById('btnQuery').disabled=false;
		document.getElementById('btnModify').disabled=true;
		document.getElementById('btnfirst').disabled=true;				
		document.getElementById('btnnext').disabled=true;					
		document.getElementById('btnprevious').disabled=true;			
		document.getElementById('btnlast').disabled=true;
		
	}
	
	return false;
	
}
