/***********mimoh 16042012****************************7196********************************/

ALTER TABLE AGENCY_MAST ADD EDTN_WISE_BILL_REQ VARCHAR(1) DEFAULT 'N'
/***********mimoh 16042012****************************7196********************************/


/***********ankit****************************add category********************************/


alter table Adv_Cat_Mast add Preodicity_Code  VARCHAR(8)
alter table Adv_Cat_Mast add RO_hr  VARCHAR(8)
alter table Adv_Cat_Mast add RO_min  VARCHAR(8)

/***********ankit****************************add category********************************/